/* gkr-item-properties.c generated by valac 0.22.1, the Vala compiler
 * generated from gkr-item-properties.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2006 Stefan Walter
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-gkr.h"
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <libsecret/secret.h>
#include <gio/gio.h>
#include "seahorse-common.h"
#include "config.h"
#include <gdk/gdk.h>
#include <ui/gcr-ui.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _secret_value_unref0(var) ((var == NULL) ? NULL : (var = (secret_value_unref (var), NULL)))
typedef struct _Block3Data Block3Data;
typedef struct _Block4Data Block4Data;

struct _SeahorseGkrItemPropertiesPrivate {
	SeahorseGkrItem* _item;
	GtkBuilder* _builder;
	GtkEntry* _password_entry;
	GtkExpander* _password_expander;
	gboolean _password_changed;
	gboolean _updating_password;
	gboolean _updating_description;
};

struct _Block3Data {
	int _ref_count_;
	SeahorseGkrItemProperties * self;
	GtkEntry* description;
};

struct _Block4Data {
	int _ref_count_;
	SeahorseGkrItemProperties * self;
	GtkEntry* description;
	GtkCheckButton* check;
};


static gpointer seahorse_gkr_item_properties_parent_class = NULL;

#define SEAHORSE_GKR_ITEM_PROPERTIES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAHORSE_GKR_TYPE_ITEM_PROPERTIES, SeahorseGkrItemPropertiesPrivate))
enum  {
	SEAHORSE_GKR_ITEM_PROPERTIES_DUMMY_PROPERTY,
	SEAHORSE_GKR_ITEM_PROPERTIES_ITEM
};
static void seahorse_gkr_item_properties_update_use (SeahorseGkrItemProperties* self);
static void seahorse_gkr_item_properties_update_type (SeahorseGkrItemProperties* self);
static void seahorse_gkr_item_properties_update_visibility (SeahorseGkrItemProperties* self);
static void seahorse_gkr_item_properties_update_server (SeahorseGkrItemProperties* self);
static void seahorse_gkr_item_properties_update_user (SeahorseGkrItemProperties* self);
static void seahorse_gkr_item_properties_update_details (SeahorseGkrItemProperties* self);
static void seahorse_gkr_item_properties_password_activate (SeahorseGkrItemProperties* self);
static void __lambda19_ (SeahorseGkrItemProperties* self, GObject* obj, GAsyncResult* res);
static void seahorse_gkr_item_properties_password_display (SeahorseGkrItemProperties* self);
static void ___lambda19__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);
static void seahorse_gkr_item_properties_description_activate (SeahorseGkrItemProperties* self, GtkEntry* description);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void __lambda20_ (Block3Data* _data3_, GObject* obj, GAsyncResult* res);
static void ___lambda20__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);
static void seahorse_gkr_item_properties_expander_activate (SeahorseGkrItemProperties* self, GtkExpander* expander);
static GObject * seahorse_gkr_item_properties_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static void _seahorse_gkr_item_properties___lambda21_ (SeahorseGkrItemProperties* self, gint response);
static void __seahorse_gkr_item_properties___lambda21__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static void _seahorse_gkr_item_properties___lambda22_ (Block4Data* _data4_);
static void __seahorse_gkr_item_properties___lambda22__gtk_entry_activate (GtkEntry* _sender, gpointer self);
static gboolean _seahorse_gkr_item_properties___lambda23_ (Block4Data* _data4_);
static gboolean __seahorse_gkr_item_properties___lambda23__gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self);
static void _seahorse_gkr_item_properties_expander_activate_gtk_expander_activate (GtkExpander* _sender, gpointer self);
static void _seahorse_gkr_item_properties___lambda24_ (Block4Data* _data4_);
static void __seahorse_gkr_item_properties___lambda24__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _seahorse_gkr_item_properties___lambda25_ (SeahorseGkrItemProperties* self, GParamSpec* pspec);
static void __seahorse_gkr_item_properties___lambda25__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void _seahorse_gkr_item_properties_password_activate_gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void _seahorse_gkr_item_properties___lambda26_ (SeahorseGkrItemProperties* self);
static void __seahorse_gkr_item_properties___lambda26__gtk_editable_changed (GtkEditable* _sender, gpointer self);
static gboolean _seahorse_gkr_item_properties___lambda27_ (SeahorseGkrItemProperties* self);
static gboolean __seahorse_gkr_item_properties___lambda27__gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self);
static void seahorse_gkr_item_properties_finalize (GObject* obj);
static void _vala_seahorse_gkr_item_properties_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seahorse_gkr_item_properties_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeahorseGkrItemProperties* seahorse_gkr_item_properties_construct (GType object_type, SeahorseGkrItem* item, GtkWindow* parent) {
	SeahorseGkrItemProperties * self = NULL;
	SeahorseGkrItem* _tmp0_ = NULL;
	GtkWindow* _tmp1_ = NULL;
	SeahorseGkrItem* _tmp2_ = NULL;
#line 122 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_val_if_fail (item != NULL, NULL);
#line 124 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = item;
#line 124 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = parent;
#line 124 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = (SeahorseGkrItemProperties*) g_object_new (object_type, "item", _tmp0_, "transient-for", _tmp1_, NULL);
#line 129 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = item;
#line 129 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_refresh (_tmp2_);
#line 122 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return self;
#line 137 "gkr-item-properties.c"
}


SeahorseGkrItemProperties* seahorse_gkr_item_properties_new (SeahorseGkrItem* item, GtkWindow* parent) {
#line 122 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return seahorse_gkr_item_properties_construct (SEAHORSE_GKR_TYPE_ITEM_PROPERTIES, item, parent);
#line 144 "gkr-item-properties.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 133 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return self ? g_object_ref (self) : NULL;
#line 151 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_update_use (SeahorseGkrItemProperties* self) {
	GtkLabel* use = NULL;
	GtkBuilder* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	SeahorseGkrItem* _tmp3_ = NULL;
	SeahorseGkrUse _tmp4_ = 0;
	SeahorseGkrUse _tmp5_ = 0;
#line 132 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 133 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_builder;
#line 133 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_builder_get_object (_tmp0_, "use-field");
#line 133 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GTK_TYPE_LABEL, GtkLabel));
#line 133 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	use = _tmp2_;
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = self->priv->_item;
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = seahorse_gkr_item_get_use (_tmp3_);
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = _tmp4_;
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	switch (_tmp5_) {
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_NETWORK:
#line 183 "gkr-item-properties.c"
		{
			GtkLabel* _tmp6_ = NULL;
			const gchar* _tmp7_ = NULL;
#line 136 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp6_ = use;
#line 136 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp7_ = _ ("Access a network share or resource");
#line 136 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp6_, _tmp7_);
#line 137 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 195 "gkr-item-properties.c"
		}
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_WEB:
#line 199 "gkr-item-properties.c"
		{
			GtkLabel* _tmp8_ = NULL;
			const gchar* _tmp9_ = NULL;
#line 139 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp8_ = use;
#line 139 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp9_ = _ ("Access a website");
#line 139 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp8_, _tmp9_);
#line 140 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 211 "gkr-item-properties.c"
		}
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_PGP:
#line 215 "gkr-item-properties.c"
		{
			GtkLabel* _tmp10_ = NULL;
			const gchar* _tmp11_ = NULL;
#line 142 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp10_ = use;
#line 142 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp11_ = _ ("Unlocks a PGP key");
#line 142 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp10_, _tmp11_);
#line 143 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 227 "gkr-item-properties.c"
		}
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_SSH:
#line 231 "gkr-item-properties.c"
		{
			GtkLabel* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
#line 145 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp12_ = use;
#line 145 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp13_ = _ ("Unlocks a Secure Shell key");
#line 145 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp12_, _tmp13_);
#line 146 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 243 "gkr-item-properties.c"
		}
#line 134 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_OTHER:
#line 247 "gkr-item-properties.c"
		{
			GtkLabel* _tmp14_ = NULL;
			const gchar* _tmp15_ = NULL;
#line 148 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp14_ = use;
#line 148 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp15_ = _ ("Saved password or login");
#line 148 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp14_, _tmp15_);
#line 149 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 259 "gkr-item-properties.c"
		}
		default:
		{
			GtkLabel* _tmp16_ = NULL;
#line 151 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp16_ = use;
#line 151 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp16_, "");
#line 152 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 270 "gkr-item-properties.c"
		}
	}
#line 132 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (use);
#line 275 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_update_type (SeahorseGkrItemProperties* self) {
	GtkLabel* type = NULL;
	GtkBuilder* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	SeahorseGkrItem* _tmp3_ = NULL;
	SeahorseGkrUse _tmp4_ = 0;
	SeahorseGkrUse _tmp5_ = 0;
#line 156 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 157 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_builder;
#line 157 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_builder_get_object (_tmp0_, "type-field");
#line 157 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GTK_TYPE_LABEL, GtkLabel));
#line 157 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	type = _tmp2_;
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = self->priv->_item;
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = seahorse_gkr_item_get_use (_tmp3_);
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = _tmp4_;
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	switch (_tmp5_) {
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_NETWORK:
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_WEB:
#line 309 "gkr-item-properties.c"
		{
			GtkLabel* _tmp6_ = NULL;
			const gchar* _tmp7_ = NULL;
#line 161 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp6_ = type;
#line 161 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp7_ = _ ("Network Credentials");
#line 161 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp6_, _tmp7_);
#line 162 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 321 "gkr-item-properties.c"
		}
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_PGP:
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_SSH:
#line 158 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_USE_OTHER:
#line 329 "gkr-item-properties.c"
		{
			GtkLabel* _tmp8_ = NULL;
			const gchar* _tmp9_ = NULL;
#line 166 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp8_ = type;
#line 166 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp9_ = _ ("Password");
#line 166 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp8_, _tmp9_);
#line 167 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 341 "gkr-item-properties.c"
		}
		default:
		{
			GtkLabel* _tmp10_ = NULL;
#line 169 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp10_ = type;
#line 169 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			gtk_label_set_label (_tmp10_, "");
#line 170 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 352 "gkr-item-properties.c"
		}
	}
#line 156 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (type);
#line 357 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_update_visibility (SeahorseGkrItemProperties* self) {
	SeahorseGkrUse use = 0;
	SeahorseGkrItem* _tmp0_ = NULL;
	SeahorseGkrUse _tmp1_ = 0;
	SeahorseGkrUse _tmp2_ = 0;
	gboolean _tmp3_ = FALSE;
	SeahorseGkrUse _tmp4_ = 0;
	gboolean visible = FALSE;
	gboolean _tmp6_ = FALSE;
	GtkBuilder* _tmp7_ = NULL;
	GObject* _tmp8_ = NULL;
	GtkBuilder* _tmp9_ = NULL;
	GObject* _tmp10_ = NULL;
	GtkBuilder* _tmp11_ = NULL;
	GObject* _tmp12_ = NULL;
	GtkBuilder* _tmp13_ = NULL;
	GObject* _tmp14_ = NULL;
#line 174 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 175 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_item;
#line 175 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = seahorse_gkr_item_get_use (_tmp0_);
#line 175 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _tmp1_;
#line 175 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	use = _tmp2_;
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = use;
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp4_ == SEAHORSE_GKR_USE_NETWORK) {
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp3_ = TRUE;
#line 394 "gkr-item-properties.c"
	} else {
		SeahorseGkrUse _tmp5_ = 0;
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp5_ = use;
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp3_ = _tmp5_ == SEAHORSE_GKR_USE_WEB;
#line 401 "gkr-item-properties.c"
	}
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp6_ = _tmp3_;
#line 176 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	visible = _tmp6_;
#line 177 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp7_ = self->priv->_builder;
#line 177 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp8_ = gtk_builder_get_object (_tmp7_, "server-label");
#line 177 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_set (_tmp8_, "visible", visible, NULL);
#line 178 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp9_ = self->priv->_builder;
#line 178 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp10_ = gtk_builder_get_object (_tmp9_, "server-field");
#line 178 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_set (_tmp10_, "visible", visible, NULL);
#line 179 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp11_ = self->priv->_builder;
#line 179 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp12_ = gtk_builder_get_object (_tmp11_, "login-label");
#line 179 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_set (_tmp12_, "visible", visible, NULL);
#line 180 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp13_ = self->priv->_builder;
#line 180 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp14_ = gtk_builder_get_object (_tmp13_, "login-field");
#line 180 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_set (_tmp14_, "visible", visible, NULL);
#line 431 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_update_server (SeahorseGkrItemProperties* self) {
	GtkLabel* server = NULL;
	GtkBuilder* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	gchar* value = NULL;
	SeahorseGkrItem* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
#line 183 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 184 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_builder;
#line 184 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_builder_get_object (_tmp0_, "server-label");
#line 184 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GTK_TYPE_LABEL, GtkLabel));
#line 184 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	server = _tmp2_;
#line 185 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = self->priv->_item;
#line 185 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = seahorse_gkr_item_get_attribute (_tmp3_, "server");
#line 185 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	value = _tmp4_;
#line 186 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = value;
#line 186 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp5_ == NULL) {
#line 466 "gkr-item-properties.c"
		gchar* _tmp6_ = NULL;
#line 187 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp6_ = g_strdup ("");
#line 187 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (value);
#line 187 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		value = _tmp6_;
#line 474 "gkr-item-properties.c"
	}
#line 188 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp7_ = server;
#line 188 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp8_ = value;
#line 188 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_label_set_label (_tmp7_, _tmp8_);
#line 183 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_free0 (value);
#line 183 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (server);
#line 486 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_update_user (SeahorseGkrItemProperties* self) {
	GtkLabel* login = NULL;
	GtkBuilder* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	gchar* value = NULL;
	SeahorseGkrItem* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
#line 191 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 192 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_builder;
#line 192 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_builder_get_object (_tmp0_, "login-label");
#line 192 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GTK_TYPE_LABEL, GtkLabel));
#line 192 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	login = _tmp2_;
#line 193 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = self->priv->_item;
#line 193 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = seahorse_gkr_item_get_attribute (_tmp3_, "user");
#line 193 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	value = _tmp4_;
#line 194 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = value;
#line 194 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp5_ == NULL) {
#line 521 "gkr-item-properties.c"
		gchar* _tmp6_ = NULL;
#line 195 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp6_ = g_strdup ("");
#line 195 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (value);
#line 195 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		value = _tmp6_;
#line 529 "gkr-item-properties.c"
	}
#line 196 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp7_ = login;
#line 196 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp8_ = value;
#line 196 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_label_set_label (_tmp7_, _tmp8_);
#line 191 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_free0 (value);
#line 191 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (login);
#line 541 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_update_details (SeahorseGkrItemProperties* self) {
	GString* contents = NULL;
	GString* _tmp0_ = NULL;
	GHashTable* attrs = NULL;
	SeahorseGkrItem* _tmp1_ = NULL;
	GHashTable* _tmp2_ = NULL;
	GHashTable* _tmp3_ = NULL;
	GHashTableIter iter = {0};
	GHashTable* _tmp4_ = NULL;
	gchar* key = NULL;
	gchar* value = NULL;
	GtkLabel* details = NULL;
	GtkBuilder* _tmp23_ = NULL;
	GObject* _tmp24_ = NULL;
	GtkLabel* _tmp25_ = NULL;
	GString* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
#line 199 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 200 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = g_string_new ("");
#line 200 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	contents = _tmp0_;
#line 201 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = self->priv->_item;
#line 201 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_get ((SecretItem*) _tmp1_, "attributes", &_tmp2_, NULL);
#line 201 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = _tmp2_;
#line 201 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	attrs = _tmp3_;
#line 202 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = attrs;
#line 202 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_hash_table_iter_init (&iter, _tmp4_);
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	while (TRUE) {
#line 582 "gkr-item-properties.c"
		gconstpointer _tmp5_ = NULL;
		gconstpointer _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		const gchar* _tmp11_ = NULL;
		gboolean _tmp12_ = FALSE;
		gboolean _tmp15_ = FALSE;
		GString* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp7_ = g_hash_table_iter_next (&iter, (gpointer*) (&_tmp5_), (gpointer*) (&_tmp6_));
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (key);
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp8_ = g_strdup (_tmp5_);
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		key = _tmp8_;
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (value);
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp9_ = g_strdup (_tmp6_);
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		value = _tmp9_;
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (!_tmp7_) {
#line 204 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			break;
#line 617 "gkr-item-properties.c"
		}
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp11_ = key;
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp12_ = g_str_has_prefix (_tmp11_, "gkr:");
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (_tmp12_) {
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp10_ = TRUE;
#line 627 "gkr-item-properties.c"
		} else {
			const gchar* _tmp13_ = NULL;
			gboolean _tmp14_ = FALSE;
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp13_ = key;
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp14_ = g_str_has_prefix (_tmp13_, "xdg:");
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp10_ = _tmp14_;
#line 637 "gkr-item-properties.c"
		}
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp15_ = _tmp10_;
#line 205 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (_tmp15_) {
#line 206 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			continue;
#line 645 "gkr-item-properties.c"
		}
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp16_ = contents;
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp17_ = key;
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp18_ = g_markup_escape_text (_tmp17_, (gssize) (-1));
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp19_ = _tmp18_;
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp20_ = value;
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp21_ = g_markup_escape_text (_tmp20_, (gssize) (-1));
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp22_ = _tmp21_;
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_string_append_printf (_tmp16_, "<b>%s</b>: %s\n", _tmp19_, _tmp22_);
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (_tmp22_);
#line 207 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (_tmp19_);
#line 667 "gkr-item-properties.c"
	}
#line 211 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp23_ = self->priv->_builder;
#line 211 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp24_ = gtk_builder_get_object (_tmp23_, "details-box");
#line 211 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp25_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp24_, GTK_TYPE_LABEL, GtkLabel));
#line 211 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	details = _tmp25_;
#line 212 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_label_set_use_markup (details, TRUE);
#line 213 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp26_ = contents;
#line 213 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp27_ = _tmp26_->str;
#line 213 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_label_set_label (details, _tmp27_);
#line 199 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (details);
#line 199 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_free0 (value);
#line 199 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_free0 (key);
#line 199 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_hash_table_unref0 (attrs);
#line 199 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_string_free0 (contents);
#line 695 "gkr-item-properties.c"
}


static void __lambda19_ (SeahorseGkrItemProperties* self, GObject* obj, GAsyncResult* res) {
	GtkExpander* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
#line 229 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (res != NULL);
#line 704 "gkr-item-properties.c"
	{
		SeahorseGkrItem* _tmp0_ = NULL;
		GAsyncResult* _tmp1_ = NULL;
#line 231 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp0_ = self->priv->_item;
#line 231 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp1_ = res;
#line 231 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		seahorse_gkr_item_set_secret_finish (_tmp0_, _tmp1_, &_inner_error_);
#line 231 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (_inner_error_ != NULL) {
#line 716 "gkr-item-properties.c"
			goto __catch8_g_error;
		}
#line 232 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		seahorse_gkr_item_properties_password_display (self);
#line 721 "gkr-item-properties.c"
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* err = NULL;
		GError* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		err = _inner_error_;
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_inner_error_ = NULL;
#line 234 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp2_ = err;
#line 234 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_dbus_error_strip_remote_error (_tmp2_);
#line 235 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp3_ = _ ("Couldn't change password.");
#line 235 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp4_ = err;
#line 235 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp5_ = _tmp4_->message;
#line 235 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		seahorse_util_show_error ((GtkWidget*) self, _tmp3_, _tmp5_);
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_error_free0 (err);
#line 749 "gkr-item-properties.c"
	}
	__finally8:
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_inner_error_ != NULL) {
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_clear_error (&_inner_error_);
#line 230 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 760 "gkr-item-properties.c"
	}
#line 238 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp6_ = self->priv->_password_expander;
#line 238 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp6_, TRUE);
#line 239 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_updating_password = FALSE;
#line 768 "gkr-item-properties.c"
}


static void ___lambda19__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
#line 229 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	__lambda19_ (self, source_object, res);
#line 229 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_unref (self);
#line 777 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_password_activate (SeahorseGkrItemProperties* self) {
	GtkExpander* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	GtkExpander* _tmp5_ = NULL;
	SecretValue* value = NULL;
	GtkEntry* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	SecretValue* _tmp9_ = NULL;
	SeahorseGkrItem* _tmp10_ = NULL;
	SecretValue* _tmp11_ = NULL;
#line 216 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 218 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_password_expander;
#line 218 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_expander_get_expanded (_tmp0_);
#line 218 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _tmp1_;
#line 218 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (!_tmp2_) {
#line 219 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 807 "gkr-item-properties.c"
	}
#line 220 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = self->priv->_password_changed;
#line 220 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (!_tmp3_) {
#line 221 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 815 "gkr-item-properties.c"
	}
#line 222 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = self->priv->_updating_password;
#line 222 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp4_) {
#line 223 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 823 "gkr-item-properties.c"
	}
#line 225 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_updating_password = TRUE;
#line 226 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = self->priv->_password_expander;
#line 226 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp5_, FALSE);
#line 228 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp6_ = self->priv->_password_entry;
#line 228 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp7_ = gtk_entry_get_text (_tmp6_);
#line 228 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp8_ = _tmp7_;
#line 228 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp9_ = secret_value_new (_tmp8_, (gssize) (-1), "text/plain");
#line 228 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	value = _tmp9_;
#line 229 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp10_ = self->priv->_item;
#line 229 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp11_ = value;
#line 229 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_set_secret (_tmp10_, _tmp11_, NULL, ___lambda19__gasync_ready_callback, g_object_ref (self));
#line 216 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_secret_value_unref0 (value);
#line 849 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_password_display (SeahorseGkrItemProperties* self) {
	GtkExpander* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GtkEntry* _tmp11_ = NULL;
#line 243 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 244 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_password_expander;
#line 244 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_expander_get_expanded (_tmp0_);
#line 244 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _tmp1_;
#line 244 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp2_) {
#line 868 "gkr-item-properties.c"
		SecretValue* secret = NULL;
		SeahorseGkrItem* _tmp3_ = NULL;
		SecretValue* _tmp4_ = NULL;
		SecretValue* _tmp5_ = NULL;
#line 245 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp3_ = self->priv->_item;
#line 245 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp4_ = seahorse_gkr_item_get_secret (_tmp3_);
#line 245 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		secret = _tmp4_;
#line 246 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp5_ = secret;
#line 246 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (_tmp5_ != NULL) {
#line 883 "gkr-item-properties.c"
			const gchar* password = NULL;
			SecretValue* _tmp6_ = NULL;
			const gchar* _tmp7_ = NULL;
			const gchar* _tmp8_ = NULL;
#line 247 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp6_ = secret;
#line 247 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp7_ = secret_value_get_text (_tmp6_);
#line 247 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			password = _tmp7_;
#line 248 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_tmp8_ = password;
#line 248 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			if (_tmp8_ != NULL) {
#line 898 "gkr-item-properties.c"
				GtkEntry* _tmp9_ = NULL;
				const gchar* _tmp10_ = NULL;
#line 249 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				_tmp9_ = self->priv->_password_entry;
#line 249 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				_tmp10_ = password;
#line 249 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				gtk_entry_set_text (_tmp9_, _tmp10_);
#line 250 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				self->priv->_password_changed = FALSE;
#line 251 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				_secret_value_unref0 (secret);
#line 251 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				return;
#line 913 "gkr-item-properties.c"
			}
		}
#line 244 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_secret_value_unref0 (secret);
#line 918 "gkr-item-properties.c"
	}
#line 255 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp11_ = self->priv->_password_entry;
#line 255 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_entry_set_text (_tmp11_, "");
#line 256 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_password_changed = FALSE;
#line 926 "gkr-item-properties.c"
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return _data3_;
#line 935 "gkr-item-properties.c"
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 944 "gkr-item-properties.c"
		SeahorseGkrItemProperties * self;
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		self = _data3_->self;
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_object_unref0 (_data3_->description);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_object_unref0 (self);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_slice_free (Block3Data, _data3_);
#line 954 "gkr-item-properties.c"
	}
}


static void __lambda20_ (Block3Data* _data3_, GObject* obj, GAsyncResult* res) {
	SeahorseGkrItemProperties * self;
	GtkEntry* _tmp11_ = NULL;
	GError * _inner_error_ = NULL;
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = _data3_->self;
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (res != NULL);
#line 967 "gkr-item-properties.c"
	{
		SeahorseGkrItem* _tmp0_ = NULL;
		GAsyncResult* _tmp1_ = NULL;
#line 269 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp0_ = self->priv->_item;
#line 269 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp1_ = res;
#line 269 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		secret_item_set_label_finish ((SecretItem*) _tmp0_, _tmp1_, &_inner_error_);
#line 269 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (_inner_error_ != NULL) {
#line 979 "gkr-item-properties.c"
			goto __catch9_g_error;
		}
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError* err = NULL;
		GtkEntry* _tmp2_ = NULL;
		SeahorseGkrItem* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		GError* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		GError* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		err = _inner_error_;
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_inner_error_ = NULL;
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp2_ = _data3_->description;
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp3_ = self->priv->_item;
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp4_ = seahorse_gkr_item_get_label (_tmp3_);
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp5_ = _tmp4_;
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp6_ = _tmp5_;
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		gtk_entry_set_text (_tmp2_, _tmp6_);
#line 271 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (_tmp6_);
#line 272 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp7_ = err;
#line 272 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_dbus_error_strip_remote_error (_tmp7_);
#line 273 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp8_ = _ ("Couldn't set description.");
#line 273 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp9_ = err;
#line 273 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp10_ = _tmp9_->message;
#line 273 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		seahorse_util_show_error ((GtkWidget*) self, _tmp8_, _tmp10_);
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_error_free0 (err);
#line 1028 "gkr-item-properties.c"
	}
	__finally9:
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_inner_error_ != NULL) {
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_clear_error (&_inner_error_);
#line 268 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 1039 "gkr-item-properties.c"
	}
#line 276 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp11_ = _data3_->description;
#line 276 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp11_, TRUE);
#line 277 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_updating_description = FALSE;
#line 1047 "gkr-item-properties.c"
}


static void ___lambda20__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	__lambda20_ (self, source_object, res);
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	block3_data_unref (self);
#line 1056 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_description_activate (SeahorseGkrItemProperties* self, GtkEntry* description) {
	Block3Data* _data3_;
	GtkEntry* _tmp0_ = NULL;
	GtkEntry* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GtkEntry* _tmp3_ = NULL;
	SeahorseGkrItem* _tmp4_ = NULL;
	GtkEntry* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (description != NULL);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data3_->_ref_count_ = 1;
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data3_->self = g_object_ref (self);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = description;
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (_data3_->description);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data3_->description = _tmp1_;
#line 261 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = self->priv->_updating_description;
#line 261 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp2_) {
#line 262 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		block3_data_unref (_data3_);
#line 262 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_data3_ = NULL;
#line 262 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 1098 "gkr-item-properties.c"
	}
#line 264 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_updating_description = TRUE;
#line 265 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = _data3_->description;
#line 265 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp3_, FALSE);
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = self->priv->_item;
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = _data3_->description;
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp6_ = gtk_entry_get_text (_tmp5_);
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp7_ = _tmp6_;
#line 267 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	secret_item_set_label ((SecretItem*) _tmp4_, _tmp7_, NULL, ___lambda20__gasync_ready_callback, block3_data_ref (_data3_));
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	block3_data_unref (_data3_);
#line 259 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data3_ = NULL;
#line 1120 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_expander_activate (SeahorseGkrItemProperties* self, GtkExpander* expander) {
	GtkExpander* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GtkCheckButton* check = NULL;
	GtkBuilder* _tmp3_ = NULL;
	GObject* _tmp4_ = NULL;
	GtkCheckButton* _tmp5_ = NULL;
	GtkCheckButton* _tmp6_ = NULL;
#line 281 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 281 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (expander != NULL);
#line 283 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = expander;
#line 283 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = gtk_expander_get_expanded (_tmp0_);
#line 283 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _tmp1_;
#line 283 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (!_tmp2_) {
#line 284 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		return;
#line 1147 "gkr-item-properties.c"
	}
#line 287 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = self->priv->_builder;
#line 287 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = gtk_builder_get_object (_tmp3_, "show-password-check");
#line 287 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, GTK_TYPE_CHECK_BUTTON, GtkCheckButton));
#line 287 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	check = _tmp5_;
#line 288 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp6_ = check;
#line 288 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp6_, FALSE);
#line 291 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_password_display (self);
#line 281 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (check);
#line 1165 "gkr-item-properties.c"
}


SeahorseGkrItem* seahorse_gkr_item_properties_get_item (SeahorseGkrItemProperties* self) {
	SeahorseGkrItem* result;
	SeahorseGkrItem* _tmp0_ = NULL;
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_item;
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	result = _tmp0_;
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return result;
#line 1180 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_set_item (SeahorseGkrItemProperties* self, SeahorseGkrItem* value) {
	SeahorseGkrItem* _tmp0_ = NULL;
	SeahorseGkrItem* _tmp1_ = NULL;
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (self != NULL);
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = value;
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_item);
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_item = _tmp1_;
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_notify ((GObject *) self, "item");
#line 1199 "gkr-item-properties.c"
}


static Block4Data* block4_data_ref (Block4Data* _data4_) {
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_atomic_int_inc (&_data4_->_ref_count_);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return _data4_;
#line 1208 "gkr-item-properties.c"
}


static void block4_data_unref (void * _userdata_) {
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
#line 1217 "gkr-item-properties.c"
		SeahorseGkrItemProperties * self;
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		self = _data4_->self;
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_object_unref0 (_data4_->check);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_object_unref0 (_data4_->description);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_object_unref0 (self);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_slice_free (Block4Data, _data4_);
#line 1229 "gkr-item-properties.c"
	}
}


static void _seahorse_gkr_item_properties___lambda21_ (SeahorseGkrItemProperties* self, gint response) {
#line 48 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 1237 "gkr-item-properties.c"
}


static void __seahorse_gkr_item_properties___lambda21__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 47 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_seahorse_gkr_item_properties___lambda21_ (self, response_id);
#line 1244 "gkr-item-properties.c"
}


static void _seahorse_gkr_item_properties___lambda22_ (Block4Data* _data4_) {
	SeahorseGkrItemProperties * self;
	GtkEntry* _tmp0_ = NULL;
#line 58 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = _data4_->self;
#line 59 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = _data4_->description;
#line 59 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_description_activate (self, _tmp0_);
#line 1257 "gkr-item-properties.c"
}


static void __seahorse_gkr_item_properties___lambda22__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 58 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_seahorse_gkr_item_properties___lambda22_ (self);
#line 1264 "gkr-item-properties.c"
}


static gboolean _seahorse_gkr_item_properties___lambda23_ (Block4Data* _data4_) {
	SeahorseGkrItemProperties * self;
	gboolean result = FALSE;
	GtkEntry* _tmp0_ = NULL;
#line 61 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = _data4_->self;
#line 62 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = _data4_->description;
#line 62 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_description_activate (self, _tmp0_);
#line 63 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	result = FALSE;
#line 63 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return result;
#line 1282 "gkr-item-properties.c"
}


static gboolean __seahorse_gkr_item_properties___lambda23__gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self) {
	gboolean result;
	result = _seahorse_gkr_item_properties___lambda23_ (self);
#line 61 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return result;
#line 1291 "gkr-item-properties.c"
}


static void _seahorse_gkr_item_properties_expander_activate_gtk_expander_activate (GtkExpander* _sender, gpointer self) {
#line 68 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_expander_activate (self, _sender);
#line 1298 "gkr-item-properties.c"
}


static void _seahorse_gkr_item_properties___lambda24_ (Block4Data* _data4_) {
	SeahorseGkrItemProperties * self;
	GtkEntry* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
#line 72 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = _data4_->self;
#line 73 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = self->priv->_password_entry;
#line 73 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = _data4_->check;
#line 73 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
#line 73 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp3_ = _tmp2_;
#line 73 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_entry_set_visibility (_tmp0_, _tmp3_);
#line 1320 "gkr-item-properties.c"
}


static void __seahorse_gkr_item_properties___lambda24__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
#line 72 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_seahorse_gkr_item_properties___lambda24_ (self);
#line 1327 "gkr-item-properties.c"
}


static void _seahorse_gkr_item_properties___lambda25_ (SeahorseGkrItemProperties* self, GParamSpec* pspec) {
	GParamSpec* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GQuark _tmp4_ = 0U;
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	static GQuark _tmp3_label0 = 0;
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	static GQuark _tmp3_label1 = 0;
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	static GQuark _tmp3_label2 = 0;
#line 80 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_return_if_fail (pspec != NULL);
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = pspec;
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp1_ = _tmp0_->name;
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp2_ = _tmp1_;
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp4_ = (NULL == _tmp2_) ? 0 : g_quark_from_string (_tmp2_);
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_tmp4_ == ((0 != _tmp3_label0) ? _tmp3_label0 : (_tmp3_label0 = g_quark_from_static_string ("use")))) {
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		switch (0) {
#line 1356 "gkr-item-properties.c"
			default:
			{
#line 83 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_update_use (self);
#line 84 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_update_type (self);
#line 85 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_update_visibility (self);
#line 86 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				break;
#line 1367 "gkr-item-properties.c"
			}
		}
	} else if (_tmp4_ == ((0 != _tmp3_label1) ? _tmp3_label1 : (_tmp3_label1 = g_quark_from_static_string ("attributes")))) {
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		switch (0) {
#line 1373 "gkr-item-properties.c"
			default:
			{
#line 88 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_update_details (self);
#line 89 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_update_server (self);
#line 90 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_update_user (self);
#line 91 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				break;
#line 1384 "gkr-item-properties.c"
			}
		}
	} else if (_tmp4_ == ((0 != _tmp3_label2) ? _tmp3_label2 : (_tmp3_label2 = g_quark_from_static_string ("has-secret")))) {
#line 81 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		switch (0) {
#line 1390 "gkr-item-properties.c"
			default:
			{
#line 93 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				seahorse_gkr_item_properties_password_display (self);
#line 94 "/data/src/seahorse/gkr/gkr-item-properties.vala"
				break;
#line 1397 "gkr-item-properties.c"
			}
		}
	}
}


static void __seahorse_gkr_item_properties___lambda25__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 80 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_seahorse_gkr_item_properties___lambda25_ (self, pspec);
#line 1407 "gkr-item-properties.c"
}


static void _seahorse_gkr_item_properties_password_activate_gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 109 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_password_activate (self);
#line 1414 "gkr-item-properties.c"
}


static void _seahorse_gkr_item_properties___lambda26_ (SeahorseGkrItemProperties* self) {
#line 111 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_password_changed = TRUE;
#line 1421 "gkr-item-properties.c"
}


static void __seahorse_gkr_item_properties___lambda26__gtk_editable_changed (GtkEditable* _sender, gpointer self) {
#line 110 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_seahorse_gkr_item_properties___lambda26_ (self);
#line 1428 "gkr-item-properties.c"
}


static gboolean _seahorse_gkr_item_properties___lambda27_ (SeahorseGkrItemProperties* self) {
	gboolean result = FALSE;
#line 114 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_password_activate (self);
#line 115 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	result = FALSE;
#line 115 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return result;
#line 1440 "gkr-item-properties.c"
}


static gboolean __seahorse_gkr_item_properties___lambda27__gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self) {
	gboolean result;
	result = _seahorse_gkr_item_properties___lambda27_ (self);
#line 113 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return result;
#line 1449 "gkr-item-properties.c"
}


static GObject * seahorse_gkr_item_properties_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SeahorseGkrItemProperties * self;
	Block4Data* _data4_;
	GtkBuilder* _tmp0_ = NULL;
	GtkWidget* content = NULL;
	GtkBuilder* _tmp6_ = NULL;
	GObject* _tmp7_ = NULL;
	GtkWidget* _tmp8_ = NULL;
	GtkBox* _tmp9_ = NULL;
	GtkWidget* _tmp10_ = NULL;
	GtkWidget* _tmp11_ = NULL;
	SeahorseGkrItem* _tmp12_ = NULL;
	GtkBuilder* _tmp13_ = NULL;
	GObject* _tmp14_ = NULL;
	GtkBuilder* _tmp15_ = NULL;
	GObject* _tmp16_ = NULL;
	GtkEntry* _tmp17_ = NULL;
	SeahorseGkrItem* _tmp18_ = NULL;
	GtkEntry* _tmp19_ = NULL;
	GtkEntry* _tmp20_ = NULL;
	GtkEntry* _tmp21_ = NULL;
	GtkBuilder* _tmp22_ = NULL;
	GObject* _tmp23_ = NULL;
	GtkExpander* _tmp24_ = NULL;
	GtkExpander* _tmp25_ = NULL;
	GtkBuilder* _tmp26_ = NULL;
	GObject* _tmp27_ = NULL;
	GtkCheckButton* _tmp28_ = NULL;
	GtkCheckButton* _tmp29_ = NULL;
	SeahorseGkrItem* _tmp30_ = NULL;
	SeahorseGkrItem* _tmp31_ = NULL;
	GcrSecureEntryBuffer* buffer = NULL;
	GcrSecureEntryBuffer* _tmp32_ = NULL;
	GcrSecureEntryBuffer* _tmp33_ = NULL;
	GtkEntry* _tmp34_ = NULL;
	GtkBox* box = NULL;
	GtkBuilder* _tmp35_ = NULL;
	GObject* _tmp36_ = NULL;
	GtkBox* _tmp37_ = NULL;
	GtkBox* _tmp38_ = NULL;
	GtkEntry* _tmp39_ = NULL;
	GtkEntry* _tmp40_ = NULL;
	GtkEntry* _tmp41_ = NULL;
	GtkEntry* _tmp42_ = NULL;
	GtkEntry* _tmp43_ = NULL;
	GtkEntry* _tmp44_ = NULL;
	SeahorseGkrItem* _tmp45_ = NULL;
	GtkEntry* _tmp46_ = NULL;
	GError * _inner_error_ = NULL;
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	parent_class = G_OBJECT_CLASS (seahorse_gkr_item_properties_parent_class);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_GKR_TYPE_ITEM_PROPERTIES, SeahorseGkrItemProperties);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data4_ = g_slice_new0 (Block4Data);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data4_->_ref_count_ = 1;
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data4_->self = g_object_ref (self);
#line 34 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp0_ = gtk_builder_new ();
#line 34 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_builder);
#line 34 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_builder = _tmp0_;
#line 1522 "gkr-item-properties.c"
	{
		gchar* path = NULL;
		gchar* _tmp1_ = NULL;
		GtkBuilder* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
#line 36 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp1_ = g_build_filename (UIDIR, "seahorse-gkr-item-properties.xml", NULL);
#line 36 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		path = _tmp1_;
#line 37 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp2_ = self->priv->_builder;
#line 37 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp3_ = path;
#line 37 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		gtk_builder_add_from_file (_tmp2_, _tmp3_, &_inner_error_);
#line 37 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		if (_inner_error_ != NULL) {
#line 37 "/data/src/seahorse/gkr/gkr-item-properties.vala"
			_g_free0 (path);
#line 1542 "gkr-item-properties.c"
			goto __catch10_g_error;
		}
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_free0 (path);
#line 1547 "gkr-item-properties.c"
	}
	goto __finally10;
	__catch10_g_error:
	{
		GError* err = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		err = _inner_error_;
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_inner_error_ = NULL;
#line 39 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp4_ = err;
#line 39 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_tmp5_ = _tmp4_->message;
#line 39 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_critical ("gkr-item-properties.vala:39: %s", _tmp5_);
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_g_error_free0 (err);
#line 1567 "gkr-item-properties.c"
	}
	__finally10:
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	if (_inner_error_ != NULL) {
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		block4_data_unref (_data4_);
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		_data4_ = NULL;
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 35 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_clear_error (&_inner_error_);
#line 1580 "gkr-item-properties.c"
	}
#line 42 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_CLOSE, (gint) GTK_RESPONSE_CLOSE);
#line 43 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp6_ = self->priv->_builder;
#line 43 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp7_ = gtk_builder_get_object (_tmp6_, "gkr-item-properties");
#line 43 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, GTK_TYPE_WIDGET, GtkWidget));
#line 43 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	content = _tmp8_;
#line 44 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp9_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
#line 44 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp10_ = content;
#line 44 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_container_add (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, GTK_TYPE_CONTAINER, GtkContainer), _tmp10_);
#line 45 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp11_ = content;
#line 45 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_show (_tmp11_);
#line 47 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) __seahorse_gkr_item_properties___lambda21__gtk_dialog_response, self, 0);
#line 52 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp12_ = self->priv->_item;
#line 52 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp13_ = self->priv->_builder;
#line 52 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp14_ = gtk_builder_get_object (_tmp13_, "key-image");
#line 52 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp12_, "icon", _tmp14_, "gicon", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 56 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp15_ = self->priv->_builder;
#line 56 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp16_ = gtk_builder_get_object (_tmp15_, "description-field");
#line 56 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp17_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, GTK_TYPE_ENTRY, GtkEntry));
#line 56 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data4_->description = _tmp17_;
#line 57 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp18_ = self->priv->_item;
#line 57 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp19_ = _data4_->description;
#line 57 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp18_, "label", (GObject*) _tmp19_, "text", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 58 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp20_ = _data4_->description;
#line 58 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_data (_tmp20_, "activate", (GCallback) __seahorse_gkr_item_properties___lambda22__gtk_entry_activate, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 61 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp21_ = _data4_->description;
#line 61 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_data ((GtkWidget*) _tmp21_, "focus-out-event", (GCallback) __seahorse_gkr_item_properties___lambda23__gtk_widget_focus_out_event, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, G_CONNECT_AFTER);
#line 67 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp22_ = self->priv->_builder;
#line 67 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp23_ = gtk_builder_get_object (_tmp22_, "password-expander");
#line 67 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp24_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp23_, GTK_TYPE_EXPANDER, GtkExpander));
#line 67 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_password_expander);
#line 67 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_password_expander = _tmp24_;
#line 68 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp25_ = self->priv->_password_expander;
#line 68 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_object (_tmp25_, "activate", (GCallback) _seahorse_gkr_item_properties_expander_activate_gtk_expander_activate, self, G_CONNECT_AFTER);
#line 71 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp26_ = self->priv->_builder;
#line 71 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp27_ = gtk_builder_get_object (_tmp26_, "show-password-check");
#line 71 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp28_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp27_, GTK_TYPE_CHECK_BUTTON, GtkCheckButton));
#line 71 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data4_->check = _tmp28_;
#line 72 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp29_ = _data4_->check;
#line 72 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_data ((GtkToggleButton*) _tmp29_, "toggled", (GCallback) __seahorse_gkr_item_properties___lambda24__gtk_toggle_button_toggled, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 77 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp30_ = self->priv->_item;
#line 77 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp30_, "label", (GObject*) self, "title", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 80 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp31_ = self->priv->_item;
#line 80 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_object ((GObject*) _tmp31_, "notify", (GCallback) __seahorse_gkr_item_properties___lambda25__g_object_notify, self, 0);
#line 99 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp32_ = (GcrSecureEntryBuffer*) gcr_secure_entry_buffer_new ();
#line 99 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	buffer = _tmp32_;
#line 100 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp33_ = buffer;
#line 100 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp34_ = (GtkEntry*) gtk_entry_new_with_buffer ((GtkEntryBuffer*) _tmp33_);
#line 100 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_ref_sink (_tmp34_);
#line 100 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_password_entry);
#line 100 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_password_entry = _tmp34_;
#line 101 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp35_ = self->priv->_builder;
#line 101 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp36_ = gtk_builder_get_object (_tmp35_, "password-box-area");
#line 101 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp37_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp36_, GTK_TYPE_BOX, GtkBox));
#line 101 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	box = _tmp37_;
#line 102 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp38_ = box;
#line 102 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp39_ = self->priv->_password_entry;
#line 102 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_container_add ((GtkContainer*) _tmp38_, (GtkWidget*) _tmp39_);
#line 103 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp40_ = self->priv->_password_entry;
#line 103 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_entry_set_visibility (_tmp40_, FALSE);
#line 104 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp41_ = self->priv->_password_entry;
#line 104 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	gtk_widget_show ((GtkWidget*) _tmp41_);
#line 105 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_password_changed = FALSE;
#line 106 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv->_updating_password = FALSE;
#line 109 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp42_ = self->priv->_password_entry;
#line 109 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_object (_tmp42_, "activate", (GCallback) _seahorse_gkr_item_properties_password_activate_gtk_entry_activate, self, 0);
#line 110 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp43_ = self->priv->_password_entry;
#line 110 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_object ((GtkEditable*) _tmp43_, "changed", (GCallback) __seahorse_gkr_item_properties___lambda26__gtk_editable_changed, self, 0);
#line 113 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp44_ = self->priv->_password_entry;
#line 113 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_signal_connect_object ((GtkWidget*) _tmp44_, "focus-out-event", (GCallback) __seahorse_gkr_item_properties___lambda27__gtk_widget_focus_out_event, self, G_CONNECT_AFTER);
#line 119 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp45_ = self->priv->_item;
#line 119 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_tmp46_ = self->priv->_password_entry;
#line 119 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp45_, "has-secret", (GObject*) _tmp46_, "sensitive", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (box);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (buffer);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (content);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	block4_data_unref (_data4_);
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_data4_ = NULL;
#line 33 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	return obj;
#line 1738 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_class_init (SeahorseGkrItemPropertiesClass * klass) {
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	seahorse_gkr_item_properties_parent_class = g_type_class_peek_parent (klass);
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_type_class_add_private (klass, sizeof (SeahorseGkrItemPropertiesPrivate));
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_seahorse_gkr_item_properties_get_property;
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_seahorse_gkr_item_properties_set_property;
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	G_OBJECT_CLASS (klass)->constructor = seahorse_gkr_item_properties_constructor;
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	G_OBJECT_CLASS (klass)->finalize = seahorse_gkr_item_properties_finalize;
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_GKR_ITEM_PROPERTIES_ITEM, g_param_spec_object ("item", "item", "item", SEAHORSE_GKR_TYPE_ITEM, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 1757 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_instance_init (SeahorseGkrItemProperties * self) {
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self->priv = SEAHORSE_GKR_ITEM_PROPERTIES_GET_PRIVATE (self);
#line 1764 "gkr-item-properties.c"
}


static void seahorse_gkr_item_properties_finalize (GObject* obj) {
	SeahorseGkrItemProperties * self;
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_GKR_TYPE_ITEM_PROPERTIES, SeahorseGkrItemProperties);
#line 24 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_item);
#line 26 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_builder);
#line 27 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_password_entry);
#line 28 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	_g_object_unref0 (self->priv->_password_expander);
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	G_OBJECT_CLASS (seahorse_gkr_item_properties_parent_class)->finalize (obj);
#line 1782 "gkr-item-properties.c"
}


GType seahorse_gkr_item_properties_get_type (void) {
	static volatile gsize seahorse_gkr_item_properties_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_gkr_item_properties_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseGkrItemPropertiesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_gkr_item_properties_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorseGkrItemProperties), 0, (GInstanceInitFunc) seahorse_gkr_item_properties_instance_init, NULL };
		GType seahorse_gkr_item_properties_type_id;
		seahorse_gkr_item_properties_type_id = g_type_register_static (GTK_TYPE_DIALOG, "SeahorseGkrItemProperties", &g_define_type_info, 0);
		g_once_init_leave (&seahorse_gkr_item_properties_type_id__volatile, seahorse_gkr_item_properties_type_id);
	}
	return seahorse_gkr_item_properties_type_id__volatile;
}


static void _vala_seahorse_gkr_item_properties_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeahorseGkrItemProperties * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_GKR_TYPE_ITEM_PROPERTIES, SeahorseGkrItemProperties);
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	switch (property_id) {
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_ITEM_PROPERTIES_ITEM:
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		g_value_set_object (value, seahorse_gkr_item_properties_get_item (self));
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		break;
#line 1809 "gkr-item-properties.c"
		default:
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		break;
#line 1815 "gkr-item-properties.c"
	}
}


static void _vala_seahorse_gkr_item_properties_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeahorseGkrItemProperties * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_GKR_TYPE_ITEM_PROPERTIES, SeahorseGkrItemProperties);
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
	switch (property_id) {
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		case SEAHORSE_GKR_ITEM_PROPERTIES_ITEM:
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		seahorse_gkr_item_properties_set_item (self, g_value_get_object (value));
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		break;
#line 1831 "gkr-item-properties.c"
		default:
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 23 "/data/src/seahorse/gkr/gkr-item-properties.vala"
		break;
#line 1837 "gkr-item-properties.c"
	}
}



