/* gkr-keyring-add.c generated by valac 0.22.1, the Vala compiler
 * generated from gkr-keyring-add.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2008 Stefan Walter
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-gkr.h"
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include "seahorse-common.h"
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <libsecret/secret.h>

typedef struct _Block7Data Block7Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Block7Data {
	int _ref_count_;
	SeahorseGkrKeyringAdd * self;
	GtkEntry* entry;
};


static gpointer seahorse_gkr_keyring_add_parent_class = NULL;

enum  {
	SEAHORSE_GKR_KEYRING_ADD_DUMMY_PROPERTY
};
static GObject * seahorse_gkr_keyring_add_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static Block7Data* block7_data_ref (Block7Data* _data7_);
static void block7_data_unref (void * _userdata_);
static void _seahorse_gkr_keyring_add___lambda4_ (Block7Data* _data7_, GtkEditable* editable);
static void __seahorse_gkr_keyring_add___lambda4__gtk_editable_changed (GtkEditable* _sender, gpointer self);
static void _seahorse_gkr_keyring_add___lambda5_ (Block7Data* _data7_, gint resp);
static void ___lambda7_ (SeahorseGkrKeyringAdd* self, GObject* obj, GAsyncResult* res);
static void ____lambda7__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);
static void __seahorse_gkr_keyring_add___lambda5__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);


SeahorseGkrKeyringAdd* seahorse_gkr_keyring_add_construct (GType object_type, GtkWindow* parent) {
	SeahorseGkrKeyringAdd * self = NULL;
	GtkWindow* _tmp0_ = NULL;
#line 68 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp0_ = parent;
#line 68 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	self = (SeahorseGkrKeyringAdd*) g_object_new (object_type, "transient-for", _tmp0_, NULL);
#line 69 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 70 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_window_present ((GtkWindow*) self);
#line 67 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	return self;
#line 76 "gkr-keyring-add.c"
}


SeahorseGkrKeyringAdd* seahorse_gkr_keyring_add_new (GtkWindow* parent) {
#line 67 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	return seahorse_gkr_keyring_add_construct (SEAHORSE_GKR_TYPE_KEYRING_ADD, parent);
#line 83 "gkr-keyring-add.c"
}


static Block7Data* block7_data_ref (Block7Data* _data7_) {
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_atomic_int_inc (&_data7_->_ref_count_);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	return _data7_;
#line 92 "gkr-keyring-add.c"
}


static void block7_data_unref (void * _userdata_) {
	Block7Data* _data7_;
	_data7_ = (Block7Data*) _userdata_;
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	if (g_atomic_int_dec_and_test (&_data7_->_ref_count_)) {
#line 101 "gkr-keyring-add.c"
		SeahorseGkrKeyringAdd * self;
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		self = _data7_->self;
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_object_unref0 (_data7_->entry);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_object_unref0 (self);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		g_slice_free (Block7Data, _data7_);
#line 111 "gkr-keyring-add.c"
	}
}


static gpointer _g_object_ref0 (gpointer self) {
#line 34 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	return self ? g_object_ref (self) : NULL;
#line 119 "gkr-keyring-add.c"
}


static void _seahorse_gkr_keyring_add___lambda4_ (Block7Data* _data7_, GtkEditable* editable) {
	SeahorseGkrKeyringAdd * self;
	gchar* name = NULL;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 36 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	self = _data7_->self;
#line 36 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_return_if_fail (editable != NULL);
#line 37 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp0_ = _data7_->entry;
#line 37 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 37 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 37 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	name = _tmp2_;
#line 38 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp3_ = name;
#line 38 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_dialog_set_response_sensitive ((GtkDialog*) self, (gint) GTK_RESPONSE_ACCEPT, g_strcmp0 (_tmp3_, "") != 0);
#line 36 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_g_free0 (name);
#line 148 "gkr-keyring-add.c"
}


static void __seahorse_gkr_keyring_add___lambda4__gtk_editable_changed (GtkEditable* _sender, gpointer self) {
#line 36 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_seahorse_gkr_keyring_add___lambda4_ (self, _sender);
#line 155 "gkr-keyring-add.c"
}


static void ___lambda7_ (SeahorseGkrKeyringAdd* self, GObject* obj, GAsyncResult* res) {
	GError * _inner_error_ = NULL;
#line 48 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_return_if_fail (res != NULL);
#line 50 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	seahorse_gkr_dialog_complete_request ((GtkWidget*) self, FALSE);
#line 165 "gkr-keyring-add.c"
	{
		GAsyncResult* _tmp0_ = NULL;
		SecretCollection* _tmp1_ = NULL;
		SecretCollection* _tmp2_ = NULL;
#line 53 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp0_ = res;
#line 53 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp1_ = secret_collection_create_finish (_tmp0_, &_inner_error_);
#line 53 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp2_ = _tmp1_;
#line 53 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_object_unref0 (_tmp2_);
#line 53 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		if (_inner_error_ != NULL) {
#line 180 "gkr-keyring-add.c"
			goto __catch14_g_error;
		}
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError* err = NULL;
		const gchar* _tmp3_ = NULL;
		GError* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		err = _inner_error_;
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_inner_error_ = NULL;
#line 55 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp3_ = _ ("Couldn't add keyring");
#line 55 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp4_ = err;
#line 55 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp5_ = _tmp4_->message;
#line 55 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		seahorse_util_show_error ((GtkWidget*) self, _tmp3_, _tmp5_);
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_error_free0 (err);
#line 205 "gkr-keyring-add.c"
	}
	__finally14:
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	if (_inner_error_ != NULL) {
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		g_clear_error (&_inner_error_);
#line 52 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		return;
#line 216 "gkr-keyring-add.c"
	}
#line 58 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_widget_destroy ((GtkWidget*) self);
#line 220 "gkr-keyring-add.c"
}


static void ____lambda7__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
#line 46 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	___lambda7_ (self, source_object, res);
#line 46 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_object_unref (self);
#line 229 "gkr-keyring-add.c"
}


static void _seahorse_gkr_keyring_add___lambda5_ (Block7Data* _data7_, gint resp) {
	SeahorseGkrKeyringAdd * self;
	gint _tmp0_ = 0;
#line 41 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	self = _data7_->self;
#line 42 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp0_ = resp;
#line 42 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	if (_tmp0_ == ((gint) GTK_RESPONSE_ACCEPT)) {
#line 242 "gkr-keyring-add.c"
		gchar* name = NULL;
		GtkEntry* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		GCancellable* cancellable = NULL;
		GCancellable* _tmp4_ = NULL;
		SecretService* service = NULL;
		SeahorseGkrBackend* _tmp5_ = NULL;
		SeahorseGkrBackend* _tmp6_ = NULL;
		SecretService* _tmp7_ = NULL;
		SecretService* _tmp8_ = NULL;
		SecretService* _tmp9_ = NULL;
		SecretService* _tmp10_ = NULL;
		SecretService* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		GCancellable* _tmp13_ = NULL;
#line 43 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp1_ = _data7_->entry;
#line 43 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp2_ = gtk_entry_get_text (_tmp1_);
#line 43 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp3_ = g_strdup (_tmp2_);
#line 43 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		name = _tmp3_;
#line 44 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp4_ = seahorse_gkr_dialog_begin_request ((GtkWidget*) self);
#line 44 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		cancellable = _tmp4_;
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp5_ = seahorse_gkr_backend_instance ();
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp6_ = _tmp5_;
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp7_ = seahorse_gkr_backend_get_service (_tmp6_);
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp8_ = _tmp7_;
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp9_ = _g_object_ref0 (_tmp8_);
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp10_ = _tmp9_;
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_object_unref0 (_tmp6_);
#line 45 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		service = _tmp10_;
#line 46 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp11_ = service;
#line 46 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp12_ = name;
#line 46 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_tmp13_ = cancellable;
#line 46 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		secret_collection_create (_tmp11_, _tmp12_, NULL, SECRET_COLLECTION_CREATE_NONE, _tmp13_, ____lambda7__gasync_ready_callback, g_object_ref (self));
#line 42 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_object_unref0 (service);
#line 42 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_object_unref0 (cancellable);
#line 42 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		_g_free0 (name);
#line 301 "gkr-keyring-add.c"
	} else {
#line 61 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
		gtk_widget_destroy ((GtkWidget*) self);
#line 305 "gkr-keyring-add.c"
	}
}


static void __seahorse_gkr_keyring_add___lambda5__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 41 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_seahorse_gkr_keyring_add___lambda5_ (self, response_id);
#line 313 "gkr-keyring-add.c"
}


static GObject * seahorse_gkr_keyring_add_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SeahorseGkrKeyringAdd * self;
	Block7Data* _data7_;
	const gchar* _tmp0_ = NULL;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp1_ = NULL;
	GtkBuilder* _tmp2_ = NULL;
	GObject* _tmp3_ = NULL;
	GtkEntry* _tmp4_ = NULL;
	GtkEntry* _tmp5_ = NULL;
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	parent_class = G_OBJECT_CLASS (seahorse_gkr_keyring_add_parent_class);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_GKR_TYPE_KEYRING_ADD, SeahorseGkrKeyringAdd);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_data7_ = g_slice_new0 (Block7Data);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_data7_->_ref_count_ = 1;
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_data7_->self = g_object_ref (self);
#line 25 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp0_ = _ ("Add Password Keyring");
#line 25 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
#line 26 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_window_set_modal ((GtkWindow*) self, TRUE);
#line 27 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER_ON_PARENT, NULL);
#line 28 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 5);
#line 30 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp1_ = seahorse_util_load_built_contents ((GtkContainer*) self, "add-keyring");
#line 30 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	builder = _tmp1_;
#line 31 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_dialog_add_buttons ((GtkDialog*) self, GTK_STOCK_OK, GTK_RESPONSE_ACCEPT, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, NULL);
#line 34 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp2_ = builder;
#line 34 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp3_ = gtk_builder_get_object (_tmp2_, "keyring-name");
#line 34 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, GTK_TYPE_ENTRY, GtkEntry));
#line 34 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_data7_->entry = _tmp4_;
#line 35 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	gtk_dialog_set_response_sensitive ((GtkDialog*) self, (gint) GTK_RESPONSE_ACCEPT, FALSE);
#line 36 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_tmp5_ = _data7_->entry;
#line 36 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_signal_connect_data ((GtkEditable*) _tmp5_, "changed", (GCallback) __seahorse_gkr_keyring_add___lambda4__gtk_editable_changed, block7_data_ref (_data7_), (GClosureNotify) block7_data_unref, 0);
#line 41 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	g_signal_connect_data ((GtkDialog*) self, "response", (GCallback) __seahorse_gkr_keyring_add___lambda5__gtk_dialog_response, block7_data_ref (_data7_), (GClosureNotify) block7_data_unref, 0);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_g_object_unref0 (builder);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	block7_data_unref (_data7_);
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	_data7_ = NULL;
#line 24 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	return obj;
#line 381 "gkr-keyring-add.c"
}


static void seahorse_gkr_keyring_add_class_init (SeahorseGkrKeyringAddClass * klass) {
#line 23 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	seahorse_gkr_keyring_add_parent_class = g_type_class_peek_parent (klass);
#line 23 "/data/src/seahorse/gkr/gkr-keyring-add.vala"
	G_OBJECT_CLASS (klass)->constructor = seahorse_gkr_keyring_add_constructor;
#line 390 "gkr-keyring-add.c"
}


static void seahorse_gkr_keyring_add_instance_init (SeahorseGkrKeyringAdd * self) {
}


GType seahorse_gkr_keyring_add_get_type (void) {
	static volatile gsize seahorse_gkr_keyring_add_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_gkr_keyring_add_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseGkrKeyringAddClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_gkr_keyring_add_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorseGkrKeyringAdd), 0, (GInstanceInitFunc) seahorse_gkr_keyring_add_instance_init, NULL };
		GType seahorse_gkr_keyring_add_type_id;
		seahorse_gkr_keyring_add_type_id = g_type_register_static (GTK_TYPE_DIALOG, "SeahorseGkrKeyringAdd", &g_define_type_info, 0);
		g_once_init_leave (&seahorse_gkr_keyring_add_type_id__volatile, seahorse_gkr_keyring_add_type_id);
	}
	return seahorse_gkr_keyring_add_type_id__volatile;
}



