/* actions.c generated by valac 0.22.1, the Vala compiler
 * generated from actions.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2008 Stefan Walter
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-common.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _SeahorseParamSpecAction SeahorseParamSpecAction;

struct _SeahorseParamSpecAction {
	GParamSpec parent_instance;
};

struct _SeahorseActionsPrivate {
	const gchar* _definition;
	GWeakRef _catalog;
};


static gpointer seahorse_action_parent_class = NULL;
static gpointer seahorse_actions_parent_class = NULL;

enum  {
	SEAHORSE_ACTION_DUMMY_PROPERTY
};
static void seahorse_action_finalize (SeahorseAction* obj);
#define SEAHORSE_ACTIONS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAHORSE_TYPE_ACTIONS, SeahorseActionsPrivate))
enum  {
	SEAHORSE_ACTIONS_DUMMY_PROPERTY,
	SEAHORSE_ACTIONS_CATALOG,
	SEAHORSE_ACTIONS_DEFINITION
};
static SeahorseActions* seahorse_actions_new (const gchar* name);
static SeahorseActions* seahorse_actions_construct (GType object_type, const gchar* name);
static void seahorse_actions_finalize (GObject* obj);
static void _vala_seahorse_actions_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seahorse_actions_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
#line 27 "/data/src/seahorse/common/actions.vala"
	return self ? g_object_ref (self) : NULL;
#line 69 "actions.c"
}


void seahorse_action_pre_activate (GtkAction* action, SeahorseCatalog* catalog, GtkWindow* window) {
	GtkAction* _tmp0_ = NULL;
	GtkWindow* _tmp1_ = NULL;
	GtkWindow* _tmp2_ = NULL;
	GtkAction* _tmp3_ = NULL;
	SeahorseCatalog* _tmp4_ = NULL;
	SeahorseCatalog* _tmp5_ = NULL;
#line 24 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (action != NULL);
#line 27 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = action;
#line 27 "/data/src/seahorse/common/actions.vala"
	_tmp1_ = window;
#line 27 "/data/src/seahorse/common/actions.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 27 "/data/src/seahorse/common/actions.vala"
	g_object_set_data_full ((GObject*) _tmp0_, "seahorse-action-window", _tmp2_, g_object_unref);
#line 28 "/data/src/seahorse/common/actions.vala"
	_tmp3_ = action;
#line 28 "/data/src/seahorse/common/actions.vala"
	_tmp4_ = catalog;
#line 28 "/data/src/seahorse/common/actions.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 28 "/data/src/seahorse/common/actions.vala"
	g_object_set_data_full ((GObject*) _tmp3_, "seahorse-action-catalog", _tmp5_, g_object_unref);
#line 98 "actions.c"
}


void seahorse_action_activate_with_window (GtkAction* action, SeahorseCatalog* catalog, GtkWindow* window) {
	GtkAction* _tmp0_ = NULL;
	SeahorseCatalog* _tmp1_ = NULL;
	GtkWindow* _tmp2_ = NULL;
	GtkAction* _tmp3_ = NULL;
	GtkAction* _tmp4_ = NULL;
#line 31 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (action != NULL);
#line 34 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = action;
#line 34 "/data/src/seahorse/common/actions.vala"
	_tmp1_ = catalog;
#line 34 "/data/src/seahorse/common/actions.vala"
	_tmp2_ = window;
#line 34 "/data/src/seahorse/common/actions.vala"
	seahorse_action_pre_activate (_tmp0_, _tmp1_, _tmp2_);
#line 35 "/data/src/seahorse/common/actions.vala"
	_tmp3_ = action;
#line 35 "/data/src/seahorse/common/actions.vala"
	gtk_action_activate (_tmp3_);
#line 36 "/data/src/seahorse/common/actions.vala"
	_tmp4_ = action;
#line 36 "/data/src/seahorse/common/actions.vala"
	seahorse_action_post_activate (_tmp4_);
#line 126 "actions.c"
}


void seahorse_action_post_activate (GtkAction* action) {
	GtkAction* _tmp0_ = NULL;
	GtkAction* _tmp1_ = NULL;
#line 39 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (action != NULL);
#line 40 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = action;
#line 40 "/data/src/seahorse/common/actions.vala"
	g_object_set_data_full ((GObject*) _tmp0_, "seahorse-action-window", NULL, NULL);
#line 41 "/data/src/seahorse/common/actions.vala"
	_tmp1_ = action;
#line 41 "/data/src/seahorse/common/actions.vala"
	g_object_set_data_full ((GObject*) _tmp1_, "seahorse-action-catalog", NULL, NULL);
#line 143 "actions.c"
}


GtkWindow* seahorse_action_get_window (GtkAction* action) {
	GtkWindow* result = NULL;
	GtkWindow* window = NULL;
	GtkAction* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	GtkWindow* _tmp2_ = NULL;
#line 44 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (action != NULL, NULL);
#line 45 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = action;
#line 45 "/data/src/seahorse/common/actions.vala"
	_tmp1_ = g_object_get_data ((GObject*) _tmp0_, "seahorse-action-window");
#line 45 "/data/src/seahorse/common/actions.vala"
	_tmp2_ = _g_object_ref0 ((GtkWindow*) _tmp1_);
#line 45 "/data/src/seahorse/common/actions.vala"
	window = _tmp2_;
#line 46 "/data/src/seahorse/common/actions.vala"
	result = window;
#line 46 "/data/src/seahorse/common/actions.vala"
	return result;
#line 167 "actions.c"
}


SeahorseCatalog* seahorse_action_get_catalog (GtkAction* action) {
	SeahorseCatalog* result = NULL;
	SeahorseCatalog* catalog = NULL;
	GtkAction* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	SeahorseCatalog* _tmp2_ = NULL;
#line 49 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (action != NULL, NULL);
#line 50 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = action;
#line 50 "/data/src/seahorse/common/actions.vala"
	_tmp1_ = g_object_get_data ((GObject*) _tmp0_, "seahorse-action-catalog");
#line 50 "/data/src/seahorse/common/actions.vala"
	_tmp2_ = _g_object_ref0 ((SeahorseCatalog*) _tmp1_);
#line 50 "/data/src/seahorse/common/actions.vala"
	catalog = _tmp2_;
#line 51 "/data/src/seahorse/common/actions.vala"
	result = catalog;
#line 51 "/data/src/seahorse/common/actions.vala"
	return result;
#line 191 "actions.c"
}


SeahorseAction* seahorse_action_construct (GType object_type) {
	SeahorseAction* self = NULL;
#line 23 "/data/src/seahorse/common/actions.vala"
	self = (SeahorseAction*) g_type_create_instance (object_type);
#line 23 "/data/src/seahorse/common/actions.vala"
	return self;
#line 201 "actions.c"
}


SeahorseAction* seahorse_action_new (void) {
#line 23 "/data/src/seahorse/common/actions.vala"
	return seahorse_action_construct (SEAHORSE_TYPE_ACTION);
#line 208 "actions.c"
}


static void seahorse_value_action_init (GValue* value) {
#line 23 "/data/src/seahorse/common/actions.vala"
	value->data[0].v_pointer = NULL;
#line 215 "actions.c"
}


static void seahorse_value_action_free_value (GValue* value) {
#line 23 "/data/src/seahorse/common/actions.vala"
	if (value->data[0].v_pointer) {
#line 23 "/data/src/seahorse/common/actions.vala"
		seahorse_action_unref (value->data[0].v_pointer);
#line 224 "actions.c"
	}
}


static void seahorse_value_action_copy_value (const GValue* src_value, GValue* dest_value) {
#line 23 "/data/src/seahorse/common/actions.vala"
	if (src_value->data[0].v_pointer) {
#line 23 "/data/src/seahorse/common/actions.vala"
		dest_value->data[0].v_pointer = seahorse_action_ref (src_value->data[0].v_pointer);
#line 234 "actions.c"
	} else {
#line 23 "/data/src/seahorse/common/actions.vala"
		dest_value->data[0].v_pointer = NULL;
#line 238 "actions.c"
	}
}


static gpointer seahorse_value_action_peek_pointer (const GValue* value) {
#line 23 "/data/src/seahorse/common/actions.vala"
	return value->data[0].v_pointer;
#line 246 "actions.c"
}


static gchar* seahorse_value_action_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 23 "/data/src/seahorse/common/actions.vala"
	if (collect_values[0].v_pointer) {
#line 253 "actions.c"
		SeahorseAction* object;
		object = collect_values[0].v_pointer;
#line 23 "/data/src/seahorse/common/actions.vala"
		if (object->parent_instance.g_class == NULL) {
#line 23 "/data/src/seahorse/common/actions.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 260 "actions.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 23 "/data/src/seahorse/common/actions.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 264 "actions.c"
		}
#line 23 "/data/src/seahorse/common/actions.vala"
		value->data[0].v_pointer = seahorse_action_ref (object);
#line 268 "actions.c"
	} else {
#line 23 "/data/src/seahorse/common/actions.vala"
		value->data[0].v_pointer = NULL;
#line 272 "actions.c"
	}
#line 23 "/data/src/seahorse/common/actions.vala"
	return NULL;
#line 276 "actions.c"
}


static gchar* seahorse_value_action_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SeahorseAction** object_p;
	object_p = collect_values[0].v_pointer;
#line 23 "/data/src/seahorse/common/actions.vala"
	if (!object_p) {
#line 23 "/data/src/seahorse/common/actions.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 287 "actions.c"
	}
#line 23 "/data/src/seahorse/common/actions.vala"
	if (!value->data[0].v_pointer) {
#line 23 "/data/src/seahorse/common/actions.vala"
		*object_p = NULL;
#line 293 "actions.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 23 "/data/src/seahorse/common/actions.vala"
		*object_p = value->data[0].v_pointer;
#line 297 "actions.c"
	} else {
#line 23 "/data/src/seahorse/common/actions.vala"
		*object_p = seahorse_action_ref (value->data[0].v_pointer);
#line 301 "actions.c"
	}
#line 23 "/data/src/seahorse/common/actions.vala"
	return NULL;
#line 305 "actions.c"
}


GParamSpec* seahorse_param_spec_action (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SeahorseParamSpecAction* spec;
#line 23 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (g_type_is_a (object_type, SEAHORSE_TYPE_ACTION), NULL);
#line 23 "/data/src/seahorse/common/actions.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 23 "/data/src/seahorse/common/actions.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 23 "/data/src/seahorse/common/actions.vala"
	return G_PARAM_SPEC (spec);
#line 319 "actions.c"
}


gpointer seahorse_value_get_action (const GValue* value) {
#line 23 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SEAHORSE_TYPE_ACTION), NULL);
#line 23 "/data/src/seahorse/common/actions.vala"
	return value->data[0].v_pointer;
#line 328 "actions.c"
}


void seahorse_value_set_action (GValue* value, gpointer v_object) {
	SeahorseAction* old;
#line 23 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SEAHORSE_TYPE_ACTION));
#line 23 "/data/src/seahorse/common/actions.vala"
	old = value->data[0].v_pointer;
#line 23 "/data/src/seahorse/common/actions.vala"
	if (v_object) {
#line 23 "/data/src/seahorse/common/actions.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SEAHORSE_TYPE_ACTION));
#line 23 "/data/src/seahorse/common/actions.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 23 "/data/src/seahorse/common/actions.vala"
		value->data[0].v_pointer = v_object;
#line 23 "/data/src/seahorse/common/actions.vala"
		seahorse_action_ref (value->data[0].v_pointer);
#line 348 "actions.c"
	} else {
#line 23 "/data/src/seahorse/common/actions.vala"
		value->data[0].v_pointer = NULL;
#line 352 "actions.c"
	}
#line 23 "/data/src/seahorse/common/actions.vala"
	if (old) {
#line 23 "/data/src/seahorse/common/actions.vala"
		seahorse_action_unref (old);
#line 358 "actions.c"
	}
}


void seahorse_value_take_action (GValue* value, gpointer v_object) {
	SeahorseAction* old;
#line 23 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SEAHORSE_TYPE_ACTION));
#line 23 "/data/src/seahorse/common/actions.vala"
	old = value->data[0].v_pointer;
#line 23 "/data/src/seahorse/common/actions.vala"
	if (v_object) {
#line 23 "/data/src/seahorse/common/actions.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SEAHORSE_TYPE_ACTION));
#line 23 "/data/src/seahorse/common/actions.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 23 "/data/src/seahorse/common/actions.vala"
		value->data[0].v_pointer = v_object;
#line 377 "actions.c"
	} else {
#line 23 "/data/src/seahorse/common/actions.vala"
		value->data[0].v_pointer = NULL;
#line 381 "actions.c"
	}
#line 23 "/data/src/seahorse/common/actions.vala"
	if (old) {
#line 23 "/data/src/seahorse/common/actions.vala"
		seahorse_action_unref (old);
#line 387 "actions.c"
	}
}


static void seahorse_action_class_init (SeahorseActionClass * klass) {
#line 23 "/data/src/seahorse/common/actions.vala"
	seahorse_action_parent_class = g_type_class_peek_parent (klass);
#line 23 "/data/src/seahorse/common/actions.vala"
	SEAHORSE_ACTION_CLASS (klass)->finalize = seahorse_action_finalize;
#line 397 "actions.c"
}


static void seahorse_action_instance_init (SeahorseAction * self) {
#line 23 "/data/src/seahorse/common/actions.vala"
	self->ref_count = 1;
#line 404 "actions.c"
}


static void seahorse_action_finalize (SeahorseAction* obj) {
	SeahorseAction * self;
#line 23 "/data/src/seahorse/common/actions.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_TYPE_ACTION, SeahorseAction);
#line 412 "actions.c"
}


GType seahorse_action_get_type (void) {
	static volatile gsize seahorse_action_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_action_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { seahorse_value_action_init, seahorse_value_action_free_value, seahorse_value_action_copy_value, seahorse_value_action_peek_pointer, "p", seahorse_value_action_collect_value, "p", seahorse_value_action_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseActionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_action_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorseAction), 0, (GInstanceInitFunc) seahorse_action_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType seahorse_action_type_id;
		seahorse_action_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SeahorseAction", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&seahorse_action_type_id__volatile, seahorse_action_type_id);
	}
	return seahorse_action_type_id__volatile;
}


gpointer seahorse_action_ref (gpointer instance) {
	SeahorseAction* self;
	self = instance;
#line 23 "/data/src/seahorse/common/actions.vala"
	g_atomic_int_inc (&self->ref_count);
#line 23 "/data/src/seahorse/common/actions.vala"
	return instance;
#line 437 "actions.c"
}


void seahorse_action_unref (gpointer instance) {
	SeahorseAction* self;
	self = instance;
#line 23 "/data/src/seahorse/common/actions.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 23 "/data/src/seahorse/common/actions.vala"
		SEAHORSE_ACTION_GET_CLASS (self)->finalize (self);
#line 23 "/data/src/seahorse/common/actions.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 450 "actions.c"
	}
}


static SeahorseActions* seahorse_actions_construct (GType object_type, const gchar* name) {
	SeahorseActions * self = NULL;
	const gchar* _tmp0_ = NULL;
#line 68 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 69 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = name;
#line 69 "/data/src/seahorse/common/actions.vala"
	self = (SeahorseActions*) g_object_new (object_type, "name", _tmp0_, NULL);
#line 68 "/data/src/seahorse/common/actions.vala"
	return self;
#line 466 "actions.c"
}


static SeahorseActions* seahorse_actions_new (const gchar* name) {
#line 68 "/data/src/seahorse/common/actions.vala"
	return seahorse_actions_construct (SEAHORSE_TYPE_ACTIONS, name);
#line 473 "actions.c"
}


void seahorse_actions_register_definition (SeahorseActions* self, const gchar* definition) {
	const gchar* _tmp0_ = NULL;
#line 74 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (self != NULL);
#line 74 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (definition != NULL);
#line 75 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = definition;
#line 75 "/data/src/seahorse/common/actions.vala"
	self->priv->_definition = _tmp0_;
#line 487 "actions.c"
}


SeahorseCatalog* seahorse_actions_get_catalog (SeahorseActions* self) {
	SeahorseCatalog* result;
	GObject* _tmp0_ = NULL;
#line 57 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 57 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = g_weak_ref_get (&self->priv->_catalog);
#line 57 "/data/src/seahorse/common/actions.vala"
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, SEAHORSE_TYPE_CATALOG, SeahorseCatalog);
#line 57 "/data/src/seahorse/common/actions.vala"
	return result;
#line 502 "actions.c"
}


void seahorse_actions_set_catalog (SeahorseActions* self, SeahorseCatalog* value) {
	SeahorseCatalog* _tmp0_ = NULL;
#line 58 "/data/src/seahorse/common/actions.vala"
	g_return_if_fail (self != NULL);
#line 58 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = value;
#line 58 "/data/src/seahorse/common/actions.vala"
	g_weak_ref_set (&self->priv->_catalog, (GObject*) _tmp0_);
#line 58 "/data/src/seahorse/common/actions.vala"
	g_object_notify ((GObject *) self, "catalog");
#line 516 "actions.c"
}


const gchar* seahorse_actions_get_definition (SeahorseActions* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 62 "/data/src/seahorse/common/actions.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 62 "/data/src/seahorse/common/actions.vala"
	_tmp0_ = self->priv->_definition;
#line 62 "/data/src/seahorse/common/actions.vala"
	result = _tmp0_;
#line 62 "/data/src/seahorse/common/actions.vala"
	return result;
#line 531 "actions.c"
}


static void seahorse_actions_class_init (SeahorseActionsClass * klass) {
#line 55 "/data/src/seahorse/common/actions.vala"
	seahorse_actions_parent_class = g_type_class_peek_parent (klass);
#line 55 "/data/src/seahorse/common/actions.vala"
	g_type_class_add_private (klass, sizeof (SeahorseActionsPrivate));
#line 55 "/data/src/seahorse/common/actions.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_seahorse_actions_get_property;
#line 55 "/data/src/seahorse/common/actions.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_seahorse_actions_set_property;
#line 55 "/data/src/seahorse/common/actions.vala"
	G_OBJECT_CLASS (klass)->finalize = seahorse_actions_finalize;
#line 55 "/data/src/seahorse/common/actions.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_ACTIONS_CATALOG, g_param_spec_object ("catalog", "catalog", "catalog", SEAHORSE_TYPE_CATALOG, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 55 "/data/src/seahorse/common/actions.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_ACTIONS_DEFINITION, g_param_spec_string ("definition", "definition", "definition", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 550 "actions.c"
}


static void seahorse_actions_instance_init (SeahorseActions * self) {
#line 55 "/data/src/seahorse/common/actions.vala"
	self->priv = SEAHORSE_ACTIONS_GET_PRIVATE (self);
#line 557 "actions.c"
}


static void seahorse_actions_finalize (GObject* obj) {
	SeahorseActions * self;
#line 55 "/data/src/seahorse/common/actions.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_TYPE_ACTIONS, SeahorseActions);
#line 66 "/data/src/seahorse/common/actions.vala"
	g_weak_ref_clear (&self->priv->_catalog);
#line 55 "/data/src/seahorse/common/actions.vala"
	G_OBJECT_CLASS (seahorse_actions_parent_class)->finalize (obj);
#line 569 "actions.c"
}


GType seahorse_actions_get_type (void) {
	static volatile gsize seahorse_actions_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_actions_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseActionsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_actions_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorseActions), 0, (GInstanceInitFunc) seahorse_actions_instance_init, NULL };
		GType seahorse_actions_type_id;
		seahorse_actions_type_id = g_type_register_static (GTK_TYPE_ACTION_GROUP, "SeahorseActions", &g_define_type_info, 0);
		g_once_init_leave (&seahorse_actions_type_id__volatile, seahorse_actions_type_id);
	}
	return seahorse_actions_type_id__volatile;
}


static void _vala_seahorse_actions_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeahorseActions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_TYPE_ACTIONS, SeahorseActions);
#line 55 "/data/src/seahorse/common/actions.vala"
	switch (property_id) {
#line 55 "/data/src/seahorse/common/actions.vala"
		case SEAHORSE_ACTIONS_CATALOG:
#line 55 "/data/src/seahorse/common/actions.vala"
		g_value_take_object (value, seahorse_actions_get_catalog (self));
#line 55 "/data/src/seahorse/common/actions.vala"
		break;
#line 55 "/data/src/seahorse/common/actions.vala"
		case SEAHORSE_ACTIONS_DEFINITION:
#line 55 "/data/src/seahorse/common/actions.vala"
		g_value_set_string (value, seahorse_actions_get_definition (self));
#line 55 "/data/src/seahorse/common/actions.vala"
		break;
#line 602 "actions.c"
		default:
#line 55 "/data/src/seahorse/common/actions.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 55 "/data/src/seahorse/common/actions.vala"
		break;
#line 608 "actions.c"
	}
}


static void _vala_seahorse_actions_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeahorseActions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_TYPE_ACTIONS, SeahorseActions);
#line 55 "/data/src/seahorse/common/actions.vala"
	switch (property_id) {
#line 55 "/data/src/seahorse/common/actions.vala"
		case SEAHORSE_ACTIONS_CATALOG:
#line 55 "/data/src/seahorse/common/actions.vala"
		seahorse_actions_set_catalog (self, g_value_get_object (value));
#line 55 "/data/src/seahorse/common/actions.vala"
		break;
#line 624 "actions.c"
		default:
#line 55 "/data/src/seahorse/common/actions.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 55 "/data/src/seahorse/common/actions.vala"
		break;
#line 630 "actions.c"
	}
}



