/* backend.c generated by valac 0.28.0, the Vala compiler
 * generated from backend.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-common.h"
#include <stdlib.h>
#include <string.h>






SeahorsePlace* seahorse_backend_lookup_place (SeahorseBackend* self, const gchar* uri) {
	g_return_val_if_fail (self != NULL, NULL);
	return SEAHORSE_BACKEND_GET_INTERFACE (self)->lookup_place (self, uri);
}


void seahorse_backend_register (SeahorseBackend* self) {
	seahorse_registry_register_object ((GObject*) self, "backend");
}


GList* seahorse_backend_get_registered (void) {
	GList* result = NULL;
	GList* _tmp0_ = NULL;
	_tmp0_ = seahorse_registry_object_instances ("backend");
	result = (GList*) _tmp0_;
	return result;
}


const gchar* seahorse_backend_get_name (SeahorseBackend* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SEAHORSE_BACKEND_GET_INTERFACE (self)->get_name (self);
}


const gchar* seahorse_backend_get_label (SeahorseBackend* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SEAHORSE_BACKEND_GET_INTERFACE (self)->get_label (self);
}


const gchar* seahorse_backend_get_description (SeahorseBackend* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SEAHORSE_BACKEND_GET_INTERFACE (self)->get_description (self);
}


GtkActionGroup* seahorse_backend_get_actions (SeahorseBackend* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return SEAHORSE_BACKEND_GET_INTERFACE (self)->get_actions (self);
}


gboolean seahorse_backend_get_loaded (SeahorseBackend* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return SEAHORSE_BACKEND_GET_INTERFACE (self)->get_loaded (self);
}


static void seahorse_backend_base_init (SeahorseBackendIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_object_interface_install_property (iface, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
		g_object_interface_install_property (iface, g_param_spec_string ("label", "label", "label", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
		g_object_interface_install_property (iface, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
		g_object_interface_install_property (iface, g_param_spec_object ("actions", "actions", "actions", gtk_action_group_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
		g_object_interface_install_property (iface, g_param_spec_boolean ("loaded", "loaded", "loaded", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	}
}


GType seahorse_backend_get_type (void) {
	static volatile gsize seahorse_backend_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_backend_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseBackendIface), (GBaseInitFunc) seahorse_backend_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType seahorse_backend_type_id;
		seahorse_backend_type_id = g_type_register_static (G_TYPE_INTERFACE, "SeahorseBackend", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (seahorse_backend_type_id, gcr_collection_get_type ());
		g_once_init_leave (&seahorse_backend_type_id__volatile, seahorse_backend_type_id);
	}
	return seahorse_backend_type_id__volatile;
}



