/* viewable.c generated by valac 0.22.1, the Vala compiler
 * generated from viewable.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2011 Collabora Ltd.
 * Copyright (C) 2012 Stefan Walter
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Stef Walter <stefw@collabora.co.uk>
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-common.h"
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block7Data Block7Data;

struct _Block7Data {
	int _ref_count_;
	GObject* object;
};



static Block7Data* block7_data_ref (Block7Data* _data7_);
static void block7_data_unref (void * _userdata_);
static void ___lambda7_ (Block7Data* _data7_);
static void ____lambda7__gtk_widget_destroy (GtkWidget* _sender, gpointer self);


GtkWindow* seahorse_viewable_create_viewer (SeahorseViewable* self, GtkWindow* parent) {
#line 26 "/data/src/seahorse/common/viewable.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 26 "/data/src/seahorse/common/viewable.vala"
	return SEAHORSE_VIEWABLE_GET_INTERFACE (self)->create_viewer (self, parent);
#line 52 "viewable.c"
}


gboolean seahorse_viewable_can_view (GObject* object) {
	gboolean result = FALSE;
	GObject* _tmp0_ = NULL;
#line 28 "/data/src/seahorse/common/viewable.vala"
	g_return_val_if_fail (object != NULL, FALSE);
#line 29 "/data/src/seahorse/common/viewable.vala"
	_tmp0_ = object;
#line 29 "/data/src/seahorse/common/viewable.vala"
	result = G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, SEAHORSE_TYPE_VIEWABLE);
#line 29 "/data/src/seahorse/common/viewable.vala"
	return result;
#line 67 "viewable.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 32 "/data/src/seahorse/common/viewable.vala"
	return self ? g_object_ref (self) : NULL;
#line 74 "viewable.c"
}


static Block7Data* block7_data_ref (Block7Data* _data7_) {
#line 32 "/data/src/seahorse/common/viewable.vala"
	g_atomic_int_inc (&_data7_->_ref_count_);
#line 32 "/data/src/seahorse/common/viewable.vala"
	return _data7_;
#line 83 "viewable.c"
}


static void block7_data_unref (void * _userdata_) {
	Block7Data* _data7_;
	_data7_ = (Block7Data*) _userdata_;
#line 32 "/data/src/seahorse/common/viewable.vala"
	if (g_atomic_int_dec_and_test (&_data7_->_ref_count_)) {
#line 32 "/data/src/seahorse/common/viewable.vala"
		_g_object_unref0 (_data7_->object);
#line 32 "/data/src/seahorse/common/viewable.vala"
		g_slice_free (Block7Data, _data7_);
#line 96 "viewable.c"
	}
}


static void ___lambda7_ (Block7Data* _data7_) {
	GObject* _tmp0_ = NULL;
#line 48 "/data/src/seahorse/common/viewable.vala"
	_tmp0_ = _data7_->object;
#line 48 "/data/src/seahorse/common/viewable.vala"
	g_object_set_data_full (_tmp0_, "viewable-window", NULL, NULL);
#line 107 "viewable.c"
}


static void ____lambda7__gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 47 "/data/src/seahorse/common/viewable.vala"
	___lambda7_ (self);
#line 114 "viewable.c"
}


gboolean seahorse_viewable_view (GObject* object, GtkWindow* parent) {
	gboolean result = FALSE;
	Block7Data* _data7_;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GtkWindow* window = NULL;
	GObject* _tmp4_ = NULL;
	gconstpointer _tmp5_ = NULL;
	GtkWindow* _tmp6_ = NULL;
	GtkWindow* _tmp7_ = NULL;
	GtkWindow* _tmp18_ = NULL;
	GtkWindow* _tmp19_ = NULL;
#line 32 "/data/src/seahorse/common/viewable.vala"
	g_return_val_if_fail (object != NULL, FALSE);
#line 32 "/data/src/seahorse/common/viewable.vala"
	_data7_ = g_slice_new0 (Block7Data);
#line 32 "/data/src/seahorse/common/viewable.vala"
	_data7_->_ref_count_ = 1;
#line 32 "/data/src/seahorse/common/viewable.vala"
	_tmp0_ = object;
#line 32 "/data/src/seahorse/common/viewable.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 32 "/data/src/seahorse/common/viewable.vala"
	_g_object_unref0 (_data7_->object);
#line 32 "/data/src/seahorse/common/viewable.vala"
	_data7_->object = _tmp1_;
#line 34 "/data/src/seahorse/common/viewable.vala"
	_tmp2_ = _data7_->object;
#line 34 "/data/src/seahorse/common/viewable.vala"
	_tmp3_ = seahorse_viewable_can_view (_tmp2_);
#line 34 "/data/src/seahorse/common/viewable.vala"
	if (!_tmp3_) {
#line 35 "/data/src/seahorse/common/viewable.vala"
		result = FALSE;
#line 35 "/data/src/seahorse/common/viewable.vala"
		block7_data_unref (_data7_);
#line 35 "/data/src/seahorse/common/viewable.vala"
		_data7_ = NULL;
#line 35 "/data/src/seahorse/common/viewable.vala"
		return result;
#line 160 "viewable.c"
	}
#line 37 "/data/src/seahorse/common/viewable.vala"
	window = NULL;
#line 39 "/data/src/seahorse/common/viewable.vala"
	_tmp4_ = _data7_->object;
#line 39 "/data/src/seahorse/common/viewable.vala"
	_tmp5_ = g_object_get_data (_tmp4_, "viewable-window");
#line 39 "/data/src/seahorse/common/viewable.vala"
	_tmp6_ = _g_object_ref0 ((GtkWindow*) _tmp5_);
#line 39 "/data/src/seahorse/common/viewable.vala"
	_g_object_unref0 (window);
#line 39 "/data/src/seahorse/common/viewable.vala"
	window = _tmp6_;
#line 40 "/data/src/seahorse/common/viewable.vala"
	_tmp7_ = window;
#line 40 "/data/src/seahorse/common/viewable.vala"
	if (_tmp7_ == NULL) {
#line 178 "viewable.c"
		SeahorseViewable* viewable = NULL;
		GObject* _tmp8_ = NULL;
		SeahorseViewable* _tmp9_ = NULL;
		SeahorseViewable* _tmp10_ = NULL;
		GtkWindow* _tmp11_ = NULL;
		GtkWindow* _tmp12_ = NULL;
		GtkWindow* _tmp13_ = NULL;
		GObject* _tmp14_ = NULL;
		GtkWindow* _tmp15_ = NULL;
		GtkWindow* _tmp16_ = NULL;
		GtkWindow* _tmp17_ = NULL;
#line 41 "/data/src/seahorse/common/viewable.vala"
		_tmp8_ = _data7_->object;
#line 41 "/data/src/seahorse/common/viewable.vala"
		_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, SEAHORSE_TYPE_VIEWABLE, SeahorseViewable));
#line 41 "/data/src/seahorse/common/viewable.vala"
		viewable = _tmp9_;
#line 42 "/data/src/seahorse/common/viewable.vala"
		_tmp10_ = viewable;
#line 42 "/data/src/seahorse/common/viewable.vala"
		_tmp11_ = parent;
#line 42 "/data/src/seahorse/common/viewable.vala"
		_tmp12_ = seahorse_viewable_create_viewer (_tmp10_, _tmp11_);
#line 42 "/data/src/seahorse/common/viewable.vala"
		_g_object_unref0 (window);
#line 42 "/data/src/seahorse/common/viewable.vala"
		window = _tmp12_;
#line 43 "/data/src/seahorse/common/viewable.vala"
		_tmp13_ = window;
#line 43 "/data/src/seahorse/common/viewable.vala"
		if (_tmp13_ == NULL) {
#line 44 "/data/src/seahorse/common/viewable.vala"
			result = FALSE;
#line 44 "/data/src/seahorse/common/viewable.vala"
			_g_object_unref0 (viewable);
#line 44 "/data/src/seahorse/common/viewable.vala"
			_g_object_unref0 (window);
#line 44 "/data/src/seahorse/common/viewable.vala"
			block7_data_unref (_data7_);
#line 44 "/data/src/seahorse/common/viewable.vala"
			_data7_ = NULL;
#line 44 "/data/src/seahorse/common/viewable.vala"
			return result;
#line 222 "viewable.c"
		}
#line 46 "/data/src/seahorse/common/viewable.vala"
		_tmp14_ = _data7_->object;
#line 46 "/data/src/seahorse/common/viewable.vala"
		_tmp15_ = window;
#line 46 "/data/src/seahorse/common/viewable.vala"
		_tmp16_ = _g_object_ref0 (_tmp15_);
#line 46 "/data/src/seahorse/common/viewable.vala"
		g_object_set_data_full (_tmp14_, "viewable-window", _tmp16_, g_object_unref);
#line 47 "/data/src/seahorse/common/viewable.vala"
		_tmp17_ = window;
#line 47 "/data/src/seahorse/common/viewable.vala"
		g_signal_connect_data ((GtkWidget*) _tmp17_, "destroy", (GCallback) ____lambda7__gtk_widget_destroy, block7_data_ref (_data7_), (GClosureNotify) block7_data_unref, 0);
#line 40 "/data/src/seahorse/common/viewable.vala"
		_g_object_unref0 (viewable);
#line 238 "viewable.c"
	}
#line 52 "/data/src/seahorse/common/viewable.vala"
	_tmp18_ = window;
#line 52 "/data/src/seahorse/common/viewable.vala"
	gtk_window_present (_tmp18_);
#line 53 "/data/src/seahorse/common/viewable.vala"
	_tmp19_ = window;
#line 53 "/data/src/seahorse/common/viewable.vala"
	gtk_widget_show ((GtkWidget*) _tmp19_);
#line 54 "/data/src/seahorse/common/viewable.vala"
	result = TRUE;
#line 54 "/data/src/seahorse/common/viewable.vala"
	_g_object_unref0 (window);
#line 54 "/data/src/seahorse/common/viewable.vala"
	block7_data_unref (_data7_);
#line 54 "/data/src/seahorse/common/viewable.vala"
	_data7_ = NULL;
#line 54 "/data/src/seahorse/common/viewable.vala"
	return result;
#line 258 "viewable.c"
}


static void seahorse_viewable_base_init (SeahorseViewableIface * iface) {
#line 25 "/data/src/seahorse/common/viewable.vala"
	static gboolean initialized = FALSE;
#line 25 "/data/src/seahorse/common/viewable.vala"
	if (!initialized) {
#line 25 "/data/src/seahorse/common/viewable.vala"
		initialized = TRUE;
#line 269 "viewable.c"
	}
}


GType seahorse_viewable_get_type (void) {
	static volatile gsize seahorse_viewable_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_viewable_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseViewableIface), (GBaseInitFunc) seahorse_viewable_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType seahorse_viewable_type_id;
		seahorse_viewable_type_id = g_type_register_static (G_TYPE_INTERFACE, "SeahorseViewable", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (seahorse_viewable_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&seahorse_viewable_type_id__volatile, seahorse_viewable_type_id);
	}
	return seahorse_viewable_type_id__volatile;
}



