/* certificate-der-exporter.c generated by valac 0.22.1, the Vala compiler
 * generated from certificate-der-exporter.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2011 Collabora Ltd.
 * Copyright (C) 2012 Stefan Walter
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Stef Walter <stefw@collabora.co.uk>
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-pkcs11.h"
#include <gcr/gcr-base.h>
#include <gio/gio.h>
#include <string.h>
#include <stdlib.h>
#include <glib/gi18n-lib.h>
#include "seahorse-common.h"
#include <gtk/gtk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
typedef struct _SeahorseCertificateDerExporterExportData SeahorseCertificateDerExporterExportData;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SeahorseCertificateDerExporterPrivate {
	GcrCertificate* _certificate;
	GList* _objects;
};

struct _SeahorseCertificateDerExporterExportData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	SeahorseCertificateDerExporter* self;
	GCancellable* cancellable;
	guchar* result;
	gint result_length1;
	GcrCertificate* _tmp0_;
	gsize _tmp1_;
	guint8* _tmp2_;
	guchar* _tmp3_;
	gint _tmp3__length1;
	guchar* _tmp4_;
	gint _tmp4__length1;
};


static gpointer seahorse_certificate_der_exporter_parent_class = NULL;
static SeahorseExporterIface* seahorse_certificate_der_exporter_seahorse_exporter_parent_iface = NULL;

#define SEAHORSE_CERTIFICATE_DER_EXPORTER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAHORSE_TYPE_CERTIFICATE_DER_EXPORTER, SeahorseCertificateDerExporterPrivate))
enum  {
	SEAHORSE_CERTIFICATE_DER_EXPORTER_DUMMY_PROPERTY,
	SEAHORSE_CERTIFICATE_DER_EXPORTER_FILENAME,
	SEAHORSE_CERTIFICATE_DER_EXPORTER_CONTENT_TYPE,
	SEAHORSE_CERTIFICATE_DER_EXPORTER_FILE_FILTER
};
static GList* seahorse_certificate_der_exporter_real_get_objects (SeahorseExporter* base);
static gboolean seahorse_certificate_der_exporter_real_add_object (SeahorseExporter* base, GObject* obj);
static void seahorse_certificate_der_exporter_real_export_data_free (gpointer _data);
static void seahorse_certificate_der_exporter_real_export (SeahorseExporter* base, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean seahorse_certificate_der_exporter_real_export_co (SeahorseCertificateDerExporterExportData* _data_);
static guchar* _vala_array_dup1 (guchar* self, int length);
static void seahorse_certificate_der_exporter_finalize (GObject* obj);
static void _vala_seahorse_certificate_der_exporter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
#line 30 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return self ? g_object_ref (self) : NULL;
#line 89 "certificate-der-exporter.c"
}


SeahorseCertificateDerExporter* seahorse_certificate_der_exporter_construct (GType object_type, GcrCertificate* certificate) {
	SeahorseCertificateDerExporter * self = NULL;
	GcrCertificate* _tmp0_ = NULL;
	GcrCertificate* _tmp1_ = NULL;
	GcrCertificate* _tmp2_ = NULL;
#line 28 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_return_val_if_fail (certificate != NULL, NULL);
#line 28 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) g_object_new (object_type, NULL);
#line 30 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp0_ = certificate;
#line 30 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 30 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_object_unref0 (self->priv->_certificate);
#line 30 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self->priv->_certificate = _tmp1_;
#line 31 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp2_ = certificate;
#line 31 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self->priv->_objects = g_list_append (self->priv->_objects, (GObject*) _tmp2_);
#line 28 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return self;
#line 116 "certificate-der-exporter.c"
}


SeahorseCertificateDerExporter* seahorse_certificate_der_exporter_new (GcrCertificate* certificate) {
#line 28 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return seahorse_certificate_der_exporter_construct (SEAHORSE_TYPE_CERTIFICATE_DER_EXPORTER, certificate);
#line 123 "certificate-der-exporter.c"
}


static GList* seahorse_certificate_der_exporter_real_get_objects (SeahorseExporter* base) {
	SeahorseCertificateDerExporter * self;
	GList* result = NULL;
	GList* _tmp0_ = NULL;
#line 70 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) base;
#line 71 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp0_ = self->priv->_objects;
#line 71 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	result = _tmp0_;
#line 71 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return result;
#line 139 "certificate-der-exporter.c"
}


static gboolean seahorse_certificate_der_exporter_real_add_object (SeahorseExporter* base, GObject* obj) {
	SeahorseCertificateDerExporter * self;
	gboolean result = FALSE;
#line 74 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) base;
#line 74 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_return_val_if_fail (obj != NULL, FALSE);
#line 75 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	result = FALSE;
#line 75 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return result;
#line 154 "certificate-der-exporter.c"
}


static void seahorse_certificate_der_exporter_real_export_data_free (gpointer _data) {
	SeahorseCertificateDerExporterExportData* _data_;
	_data_ = _data;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_object_unref0 (_data_->cancellable);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->result = (g_free (_data_->result), NULL);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_object_unref0 (_data_->self);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_slice_free (SeahorseCertificateDerExporterExportData, _data_);
#line 169 "certificate-der-exporter.c"
}


static void seahorse_certificate_der_exporter_real_export (SeahorseExporter* base, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	SeahorseCertificateDerExporter * self;
	SeahorseCertificateDerExporterExportData* _data_;
	SeahorseCertificateDerExporter* _tmp0_ = NULL;
	GCancellable* _tmp1_ = NULL;
	GCancellable* _tmp2_ = NULL;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) base;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_ = g_slice_new0 (SeahorseCertificateDerExporterExportData);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, seahorse_certificate_der_exporter_real_export);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, seahorse_certificate_der_exporter_real_export_data_free);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->self = _tmp0_;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp1_ = cancellable;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_object_unref0 (_data_->cancellable);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->cancellable = _tmp2_;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	seahorse_certificate_der_exporter_real_export_co (_data_);
#line 201 "certificate-der-exporter.c"
}


static guchar* seahorse_certificate_der_exporter_real_export_finish (SeahorseExporter* base, GAsyncResult* _res_, int* result_length1, GError** error) {
	guchar* result;
	SeahorseCertificateDerExporterExportData* _data_;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		return NULL;
#line 212 "certificate-der-exporter.c"
	}
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	result = _data_->result;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	*result_length1 = _data_->result_length1;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->result = NULL;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return result;
#line 224 "certificate-der-exporter.c"
}


static guchar* _vala_array_dup1 (guchar* self, int length) {
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return g_memdup (self, length * sizeof (guchar));
#line 231 "certificate-der-exporter.c"
}


static gboolean seahorse_certificate_der_exporter_real_export_co (SeahorseCertificateDerExporterExportData* _data_) {
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	switch (_data_->_state_) {
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		case 0:
#line 240 "certificate-der-exporter.c"
		goto _state_0;
		default:
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_assert_not_reached ();
#line 245 "certificate-der-exporter.c"
	}
	_state_0:
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp0_ = NULL;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp0_ = _data_->self->priv->_certificate;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	memset (&_data_->_tmp1_, 0, sizeof (gsize));
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp2_ = NULL;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp2_ = gcr_certificate_get_der_data (_data_->_tmp0_, &_data_->_tmp1_);
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp3_ = NULL;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp3__length1 = 0;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp3_ = (_data_->_tmp2_ != NULL) ? _vala_array_dup1 (_data_->_tmp2_, _data_->_tmp1_) : ((gpointer) _data_->_tmp2_);
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp3__length1 = _data_->_tmp1_;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp4_ = NULL;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp4__length1 = 0;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp4_ = _data_->_tmp3_;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->_tmp4__length1 = _data_->_tmp3__length1;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->result_length1 = _data_->_tmp4__length1;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_data_->result = _data_->_tmp4_;
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	if (_data_->_state_ == 0) {
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 282 "certificate-der-exporter.c"
	} else {
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 286 "certificate-der-exporter.c"
	}
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_object_unref (_data_->_async_result);
#line 80 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return FALSE;
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	if (_data_->_state_ == 0) {
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 296 "certificate-der-exporter.c"
	} else {
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 300 "certificate-der-exporter.c"
	}
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_object_unref (_data_->_async_result);
#line 78 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return FALSE;
#line 306 "certificate-der-exporter.c"
}


static gchar* string_delimit (const gchar* self, const gchar* delimiters, gchar new_delimiter) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar _tmp3_ = '\0';
#line 1092 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1092 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	g_return_val_if_fail (delimiters != NULL, NULL);
#line 1093 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1093 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1094 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1094 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	_tmp2_ = delimiters;
#line 1094 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	_tmp3_ = new_delimiter;
#line 1094 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	g_strdelimit (_tmp1_, _tmp2_, _tmp3_);
#line 1095 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	result = _result_;
#line 1095 "/usr/share/vala-0.22/vapi/glib-2.0.vapi"
	return result;
#line 337 "certificate-der-exporter.c"
}


static gchar* seahorse_certificate_der_exporter_real_get_filename (SeahorseExporter* base) {
	gchar* result;
	SeahorseCertificateDerExporter* self;
	gchar* label = NULL;
	GcrCertificate* _tmp0_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* filename = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
#line 35 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) base;
#line 36 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	label = NULL;
#line 37 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp0_ = self->priv->_certificate;
#line 37 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	if (_tmp0_ != NULL) {
#line 359 "certificate-der-exporter.c"
		GcrCertificate* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
#line 38 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_tmp1_ = self->priv->_certificate;
#line 38 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_object_get (_tmp1_, "label", &_tmp2_, NULL);
#line 38 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_tmp3_ = _tmp2_;
#line 38 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_g_free0 (label);
#line 38 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		label = _tmp3_;
#line 39 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_tmp4_ = label;
#line 39 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		if (_tmp4_ == NULL) {
#line 378 "certificate-der-exporter.c"
			GcrCertificate* _tmp5_ = NULL;
			gchar* _tmp6_ = NULL;
			gchar* _tmp7_ = NULL;
#line 40 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
			_tmp5_ = self->priv->_certificate;
#line 40 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
			g_object_get (_tmp5_, "description", &_tmp6_, NULL);
#line 40 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
			_tmp7_ = _tmp6_;
#line 40 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
			_g_free0 (label);
#line 40 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
			label = _tmp7_;
#line 392 "certificate-der-exporter.c"
		}
	}
#line 42 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp8_ = label;
#line 42 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	if (_tmp8_ == NULL) {
#line 399 "certificate-der-exporter.c"
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
#line 43 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_tmp9_ = _ ("Certificate");
#line 43 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_tmp10_ = g_strdup (_tmp9_);
#line 43 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		_g_free0 (label);
#line 43 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		label = _tmp10_;
#line 410 "certificate-der-exporter.c"
	}
#line 45 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp11_ = label;
#line 45 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp12_ = g_strconcat (_tmp11_, ".crt", NULL);
#line 45 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	filename = _tmp12_;
#line 46 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp13_ = string_delimit (filename, SEAHORSE_BAD_FILENAME_CHARS, '_');
#line 46 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	result = _tmp13_;
#line 46 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_free0 (filename);
#line 46 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_free0 (label);
#line 46 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return result;
#line 428 "certificate-der-exporter.c"
}


static const gchar* seahorse_certificate_der_exporter_real_get_content_type (SeahorseExporter* base) {
	const gchar* result;
	SeahorseCertificateDerExporter* self;
#line 51 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) base;
#line 51 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	result = "application/pkix-cert";
#line 51 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return result;
#line 441 "certificate-der-exporter.c"
}


static GtkFileFilter* seahorse_certificate_der_exporter_real_get_file_filter (SeahorseExporter* base) {
	GtkFileFilter* result;
	SeahorseCertificateDerExporter* self;
	GtkFileFilter* filter = NULL;
	GtkFileFilter* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 55 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = (SeahorseCertificateDerExporter*) base;
#line 56 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp0_ = gtk_file_filter_new ();
#line 56 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_object_ref_sink (_tmp0_);
#line 56 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	filter = _tmp0_;
#line 57 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_tmp1_ = _ ("Certificates (DER encoded)");
#line 57 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_buildable_set_name ((GtkBuildable*) filter, _tmp1_);
#line 58 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_file_filter_add_mime_type (filter, "application/pkix-cert");
#line 59 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_file_filter_add_mime_type (filter, "application/x-x509-ca-cert");
#line 60 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_file_filter_add_mime_type (filter, "application/x-x509-user-cert");
#line 61 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_file_filter_add_pattern (filter, "*.cer");
#line 62 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_file_filter_add_pattern (filter, "*.crt");
#line 63 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	gtk_file_filter_add_pattern (filter, "*.cert");
#line 65 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	result = filter;
#line 65 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	return result;
#line 479 "certificate-der-exporter.c"
}


static void seahorse_certificate_der_exporter_class_init (SeahorseCertificateDerExporterClass * klass) {
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	seahorse_certificate_der_exporter_parent_class = g_type_class_peek_parent (klass);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_type_class_add_private (klass, sizeof (SeahorseCertificateDerExporterPrivate));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_seahorse_certificate_der_exporter_get_property;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	G_OBJECT_CLASS (klass)->finalize = seahorse_certificate_der_exporter_finalize;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_CERTIFICATE_DER_EXPORTER_FILENAME, g_param_spec_string ("filename", "filename", "filename", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_CERTIFICATE_DER_EXPORTER_CONTENT_TYPE, g_param_spec_string ("content-type", "content-type", "content-type", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_CERTIFICATE_DER_EXPORTER_FILE_FILTER, g_param_spec_object ("file-filter", "file-filter", "file-filter", GTK_TYPE_FILE_FILTER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 498 "certificate-der-exporter.c"
}


static void seahorse_certificate_der_exporter_seahorse_exporter_interface_init (SeahorseExporterIface * iface) {
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	seahorse_certificate_der_exporter_seahorse_exporter_parent_iface = g_type_interface_peek_parent (iface);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->get_objects = (GList* (*)(SeahorseExporter*)) seahorse_certificate_der_exporter_real_get_objects;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->add_object = (gboolean (*)(SeahorseExporter*, GObject*)) seahorse_certificate_der_exporter_real_add_object;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->export = (guint8* (*)(SeahorseExporter*, GCancellable*, size_t*, GError**)) seahorse_certificate_der_exporter_real_export;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->export_finish = seahorse_certificate_der_exporter_real_export_finish;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->get_filename = seahorse_certificate_der_exporter_real_get_filename;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->get_content_type = seahorse_certificate_der_exporter_real_get_content_type;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	iface->get_file_filter = seahorse_certificate_der_exporter_real_get_file_filter;
#line 519 "certificate-der-exporter.c"
}


static void seahorse_certificate_der_exporter_instance_init (SeahorseCertificateDerExporter * self) {
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self->priv = SEAHORSE_CERTIFICATE_DER_EXPORTER_GET_PRIVATE (self);
#line 526 "certificate-der-exporter.c"
}


static void seahorse_certificate_der_exporter_finalize (GObject* obj) {
	SeahorseCertificateDerExporter * self;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_TYPE_CERTIFICATE_DER_EXPORTER, SeahorseCertificateDerExporter);
#line 25 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_object_unref0 (self->priv->_certificate);
#line 26 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	_g_list_free0 (self->priv->_objects);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	G_OBJECT_CLASS (seahorse_certificate_der_exporter_parent_class)->finalize (obj);
#line 540 "certificate-der-exporter.c"
}


GType seahorse_certificate_der_exporter_get_type (void) {
	static volatile gsize seahorse_certificate_der_exporter_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_certificate_der_exporter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorseCertificateDerExporterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_certificate_der_exporter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorseCertificateDerExporter), 0, (GInstanceInitFunc) seahorse_certificate_der_exporter_instance_init, NULL };
		static const GInterfaceInfo seahorse_exporter_info = { (GInterfaceInitFunc) seahorse_certificate_der_exporter_seahorse_exporter_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType seahorse_certificate_der_exporter_type_id;
		seahorse_certificate_der_exporter_type_id = g_type_register_static (G_TYPE_OBJECT, "SeahorseCertificateDerExporter", &g_define_type_info, 0);
		g_type_add_interface_static (seahorse_certificate_der_exporter_type_id, SEAHORSE_TYPE_EXPORTER, &seahorse_exporter_info);
		g_once_init_leave (&seahorse_certificate_der_exporter_type_id__volatile, seahorse_certificate_der_exporter_type_id);
	}
	return seahorse_certificate_der_exporter_type_id__volatile;
}


static void _vala_seahorse_certificate_der_exporter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeahorseCertificateDerExporter * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_TYPE_CERTIFICATE_DER_EXPORTER, SeahorseCertificateDerExporter);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
	switch (property_id) {
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		case SEAHORSE_CERTIFICATE_DER_EXPORTER_FILENAME:
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_value_take_string (value, seahorse_exporter_get_filename ((SeahorseExporter*) self));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		break;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		case SEAHORSE_CERTIFICATE_DER_EXPORTER_CONTENT_TYPE:
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_value_set_string (value, seahorse_exporter_get_content_type ((SeahorseExporter*) self));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		break;
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		case SEAHORSE_CERTIFICATE_DER_EXPORTER_FILE_FILTER:
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		g_value_take_object (value, seahorse_exporter_get_file_filter ((SeahorseExporter*) self));
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		break;
#line 581 "certificate-der-exporter.c"
		default:
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/data/src/seahorse/pkcs11/certificate-der-exporter.vala"
		break;
#line 587 "certificate-der-exporter.c"
	}
}



