/* pkcs11-properties.c generated by valac 0.22.1, the Vala compiler
 * generated from pkcs11-properties.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2008 Stefan Walter
 * Copyright (C) 2013 Red Hat Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * Author: Stef Walter <stefw@redhat.com>
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-pkcs11.h"
#include <gck/gck.h>
#include <gtk/gtk.h>
#include <ui/gcr-ui.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include "seahorse-common.h"
#include <gcr/gcr-base.h>
#include "config.h"

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_GckAttributes_free0(var) ((var == NULL) ? NULL : (var = (_vala_GckAttributes_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
typedef struct _Block1Data Block1Data;

#define SEAHORSE_PKCS11_TYPE_KEY_DELETER (seahorse_pkcs11_key_deleter_get_type ())
#define SEAHORSE_PKCS11_KEY_DELETER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAHORSE_PKCS11_TYPE_KEY_DELETER, SeahorsePkcs11KeyDeleter))
#define SEAHORSE_PKCS11_KEY_DELETER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAHORSE_PKCS11_TYPE_KEY_DELETER, SeahorsePkcs11KeyDeleterClass))
#define SEAHORSE_PKCS11_IS_KEY_DELETER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAHORSE_PKCS11_TYPE_KEY_DELETER))
#define SEAHORSE_PKCS11_IS_KEY_DELETER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAHORSE_PKCS11_TYPE_KEY_DELETER))
#define SEAHORSE_PKCS11_KEY_DELETER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAHORSE_PKCS11_TYPE_KEY_DELETER, SeahorsePkcs11KeyDeleterClass))

typedef struct _SeahorsePkcs11KeyDeleter SeahorsePkcs11KeyDeleter;
typedef struct _SeahorsePkcs11KeyDeleterClass SeahorsePkcs11KeyDeleterClass;
typedef struct _Block2Data Block2Data;

struct _SeahorsePkcs11PropertiesPrivate {
	GckObject* _object;
	GtkBox* _content;
	GcrViewer* _viewer;
	GCancellable* _cancellable;
	GckObject* _request_key;
	GtkUIManager* _ui_manager;
	GtkActionGroup* _actions;
};

struct _Block1Data {
	int _ref_count_;
	SeahorsePkcs11Properties * self;
	SeahorsePkcs11Deleter* deleter;
};

struct _Block2Data {
	int _ref_count_;
	SeahorsePkcs11Properties * self;
	GObject* object;
};


static gpointer seahorse_pkcs11_properties_parent_class = NULL;
static gchar* seahorse_pkcs11_properties_UI_STRING;
static gchar* seahorse_pkcs11_properties_UI_STRING = NULL;

#define SEAHORSE_PKCS11_PROPERTIES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAHORSE_PKCS11_TYPE_PROPERTIES, SeahorsePkcs11PropertiesPrivate))
enum  {
	SEAHORSE_PKCS11_PROPERTIES_DUMMY_PROPERTY,
	SEAHORSE_PKCS11_PROPERTIES_OBJECT
};
static void seahorse_pkcs11_properties_on_export_certificate (SeahorsePkcs11Properties* self, GtkAction* action);
static void _seahorse_pkcs11_properties_on_export_certificate_gtk_action_callback (GtkAction* action, gpointer self);
static void seahorse_pkcs11_properties_on_delete_objects (SeahorsePkcs11Properties* self, GtkAction* action);
static void _seahorse_pkcs11_properties_on_delete_objects_gtk_action_callback (GtkAction* action, gpointer self);
static void seahorse_pkcs11_properties_on_request_certificate (SeahorsePkcs11Properties* self, GtkAction* action);
static void _seahorse_pkcs11_properties_on_request_certificate_gtk_action_callback (GtkAction* action, gpointer self);
static void seahorse_pkcs11_properties_real_dispose (GObject* base);
static void seahorse_pkcs11_properties_update_label (SeahorsePkcs11Properties* self);
static void seahorse_pkcs11_properties_add_renderer_for_object (SeahorsePkcs11Properties* self, GObject* object);
static void _vala_GckAttributes_free (GckAttributes* self);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
SeahorsePkcs11KeyDeleter* seahorse_pkcs11_key_deleter_new (GckObject* cert_or_key);
SeahorsePkcs11KeyDeleter* seahorse_pkcs11_key_deleter_construct (GType object_type, GckObject* cert_or_key);
GType seahorse_pkcs11_key_deleter_get_type (void) G_GNUC_CONST;
static void ___lambda2_ (Block1Data* _data1_, GObject* obj, GAsyncResult* res);
static void ____lambda2__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);
static void seahorse_pkcs11_properties_check_certificate_request_capable (SeahorsePkcs11Properties* self, GObject* object);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda6_ (Block2Data* _data2_, GObject* obj, GAsyncResult* res);
static void ___lambda6__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);
static GObject * seahorse_pkcs11_properties_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _seahorse_pkcs11_properties___lambda7_ (SeahorsePkcs11Properties* self, GtkWidget* widget);
static void __seahorse_pkcs11_properties___lambda7__gtk_ui_manager_add_widget (GtkUIManager* _sender, GtkWidget* widget, gpointer self);
static void _seahorse_pkcs11_properties___lambda8_ (SeahorsePkcs11Properties* self);
static void __seahorse_pkcs11_properties___lambda8__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void seahorse_pkcs11_properties_finalize (GObject* obj);
static void _vala_seahorse_pkcs11_properties_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seahorse_pkcs11_properties_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);

static const GtkActionEntry SEAHORSE_PKCS11_PROPERTIES_UI_ACTIONS[3] = {{"export-object", GTK_STOCK_SAVE_AS, "_Export", "", "Export the certificate", (GCallback) _seahorse_pkcs11_properties_on_export_certificate_gtk_action_callback}, {"delete-object", GTK_STOCK_DELETE, "_Delete", "<Ctrl>Delete", "Delete this certificate or key", (GCallback) _seahorse_pkcs11_properties_on_delete_objects_gtk_action_callback}, {"request-certificate", NULL, "Request _Certificate", NULL, "Create a certificate request file for this key", (GCallback) _seahorse_pkcs11_properties_on_request_certificate_gtk_action_callback}};

static void _seahorse_pkcs11_properties_on_export_certificate_gtk_action_callback (GtkAction* action, gpointer self) {
#line 198 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_on_export_certificate (self, action);
#line 131 "pkcs11-properties.c"
}


static void _seahorse_pkcs11_properties_on_delete_objects_gtk_action_callback (GtkAction* action, gpointer self) {
#line 198 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_on_delete_objects (self, action);
#line 138 "pkcs11-properties.c"
}


static void _seahorse_pkcs11_properties_on_request_certificate_gtk_action_callback (GtkAction* action, gpointer self) {
#line 198 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_on_request_certificate (self, action);
#line 145 "pkcs11-properties.c"
}


SeahorsePkcs11Properties* seahorse_pkcs11_properties_construct (GType object_type, GckObject* object, GtkWindow* window) {
	SeahorsePkcs11Properties * self = NULL;
	GckObject* _tmp0_ = NULL;
	GtkWindow* _tmp1_ = NULL;
#line 48 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_val_if_fail (object != NULL, NULL);
#line 48 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_val_if_fail (window != NULL, NULL);
#line 50 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = object;
#line 50 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = window;
#line 50 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self = (SeahorsePkcs11Properties*) g_object_new (object_type, "object", _tmp0_, "transient-for", _tmp1_, NULL);
#line 48 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return self;
#line 165 "pkcs11-properties.c"
}


SeahorsePkcs11Properties* seahorse_pkcs11_properties_new (GckObject* object, GtkWindow* window) {
#line 48 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return seahorse_pkcs11_properties_construct (SEAHORSE_PKCS11_TYPE_PROPERTIES, object, window);
#line 172 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_real_dispose (GObject* base) {
	SeahorsePkcs11Properties * self;
	GCancellable* _tmp0_ = NULL;
#line 124 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self = (SeahorsePkcs11Properties*) base;
#line 125 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = self->priv->_cancellable;
#line 125 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_cancellable_cancel (_tmp0_);
#line 126 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (seahorse_pkcs11_properties_parent_class)->dispose ((GObject*) G_TYPE_CHECK_INSTANCE_CAST (self, GTK_TYPE_WINDOW, GtkWindow));
#line 187 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_update_label (SeahorsePkcs11Properties* self) {
	gchar* label = NULL;
	gchar* description = NULL;
	GckObject* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_ = NULL;
	gboolean _tmp4_ = FALSE;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
#line 129 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 132 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = self->priv->_object;
#line 132 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_get ((GObject*) _tmp0_, "label", &label, "description", &description, NULL);
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp2_ = label;
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp2_ == NULL) {
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp1_ = TRUE;
#line 214 "pkcs11-properties.c"
	} else {
		const gchar* _tmp3_ = NULL;
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp3_ = label;
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp1_ = g_strcmp0 (_tmp3_, "") == 0;
#line 221 "pkcs11-properties.c"
	}
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp4_ = _tmp1_;
#line 133 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp4_) {
#line 227 "pkcs11-properties.c"
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 134 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp5_ = _ ("Unnamed");
#line 134 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp6_ = g_strdup (_tmp5_);
#line 134 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_free0 (label);
#line 134 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		label = _tmp6_;
#line 238 "pkcs11-properties.c"
	}
#line 135 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp7_ = label;
#line 135 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp8_ = description;
#line 135 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp9_ = g_strdup_printf ("%s - %s", _tmp7_, _tmp8_);
#line 135 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp10_ = _tmp9_;
#line 135 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp10_);
#line 135 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_free0 (_tmp10_);
#line 129 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_free0 (description);
#line 129 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_free0 (label);
#line 256 "pkcs11-properties.c"
}


static void _vala_GckAttributes_free (GckAttributes* self) {
#line 138 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_boxed_free (gck_attributes_get_type (), self);
#line 263 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_add_renderer_for_object (SeahorsePkcs11Properties* self, GObject* object) {
	GckAttributes* attributes = NULL;
	gchar* label = NULL;
	GObject* _tmp0_ = NULL;
	GckAttributes* _tmp1_ = NULL;
#line 138 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 138 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (object != NULL);
#line 139 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	attributes = NULL;
#line 140 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	label = NULL;
#line 142 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = object;
#line 142 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_get (_tmp0_, "label", &label, "attributes", &attributes, NULL);
#line 143 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = attributes;
#line 143 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp1_ != NULL) {
#line 288 "pkcs11-properties.c"
		GcrRenderer* renderer = NULL;
		const gchar* _tmp2_ = NULL;
		GckAttributes* _tmp3_ = NULL;
		GcrRenderer* _tmp4_ = NULL;
		GcrRenderer* _tmp5_ = NULL;
#line 144 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp2_ = label;
#line 144 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp3_ = attributes;
#line 144 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp4_ = gcr_renderer_create (_tmp2_, _tmp3_);
#line 144 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		renderer = _tmp4_;
#line 145 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp5_ = renderer;
#line 145 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_tmp5_ != NULL) {
#line 306 "pkcs11-properties.c"
			GObject* _tmp6_ = NULL;
			GcrRenderer* _tmp7_ = NULL;
			GObject* _tmp8_ = NULL;
			GcrRenderer* _tmp9_ = NULL;
			GcrRenderer* _tmp10_ = NULL;
			GObjectClass* _tmp11_ = NULL;
			GParamSpec* _tmp12_ = NULL;
			GcrViewer* _tmp15_ = NULL;
			GcrRenderer* _tmp16_ = NULL;
#line 146 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp6_ = object;
#line 146 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp7_ = renderer;
#line 146 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			g_object_bind_property_with_closures (_tmp6_, "label", (GObject*) _tmp7_, "label", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 148 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp8_ = object;
#line 148 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp9_ = renderer;
#line 148 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			g_object_bind_property_with_closures (_tmp8_, "attributes", (GObject*) _tmp9_, "attributes", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 151 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp10_ = renderer;
#line 151 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp11_ = G_OBJECT_GET_CLASS ((GObject*) _tmp10_);
#line 151 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp12_ = g_object_class_find_property (_tmp11_, "object");
#line 151 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			if (_tmp12_ != NULL) {
#line 336 "pkcs11-properties.c"
				GcrRenderer* _tmp13_ = NULL;
				GObject* _tmp14_ = NULL;
#line 152 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
				_tmp13_ = renderer;
#line 152 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
				_tmp14_ = object;
#line 152 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
				g_object_set ((GObject*) _tmp13_, "object", _tmp14_, NULL);
#line 345 "pkcs11-properties.c"
			}
#line 154 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp15_ = self->priv->_viewer;
#line 154 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp16_ = renderer;
#line 154 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			gcr_viewer_add_renderer (_tmp15_, _tmp16_);
#line 353 "pkcs11-properties.c"
		}
#line 143 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (renderer);
#line 357 "pkcs11-properties.c"
	}
#line 138 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_free0 (label);
#line 138 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	__vala_GckAttributes_free0 (attributes);
#line 363 "pkcs11-properties.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 161 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return self ? g_object_ref (self) : NULL;
#line 370 "pkcs11-properties.c"
}


static void _g_object_unref0_ (gpointer var) {
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 377 "pkcs11-properties.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_list_free (self);
#line 386 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_on_export_certificate (SeahorsePkcs11Properties* self, GtkAction* action) {
	GList* objects = NULL;
	GckObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
#line 159 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 159 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (action != NULL);
#line 160 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	objects = NULL;
#line 161 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = self->priv->_object;
#line 161 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = _g_object_ref0 ((GObject*) _tmp0_);
#line 161 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	objects = g_list_append (objects, _tmp1_);
#line 407 "pkcs11-properties.c"
	{
#line 163 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_exportable_export_to_prompt_wait (objects, (GtkWindow*) self, &_inner_error_);
#line 163 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_inner_error_ != NULL) {
#line 413 "pkcs11-properties.c"
			goto __catch1_g_error;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* err = NULL;
		const gchar* _tmp2_ = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		err = _inner_error_;
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_inner_error_ = NULL;
#line 165 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp2_ = _ ("Failed to export certificate");
#line 165 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp3_ = err;
#line 165 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp4_ = _tmp3_->message;
#line 165 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_util_show_error ((GtkWidget*) self, _tmp2_, _tmp4_);
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_error_free0 (err);
#line 438 "pkcs11-properties.c"
	}
	__finally1:
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_inner_error_ != NULL) {
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		__g_list_free__g_object_unref0_0 (objects);
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_clear_error (&_inner_error_);
#line 162 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		return;
#line 451 "pkcs11-properties.c"
	}
#line 159 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	__g_list_free__g_object_unref0_0 (objects);
#line 455 "pkcs11-properties.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return _data1_;
#line 464 "pkcs11-properties.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 473 "pkcs11-properties.c"
		SeahorsePkcs11Properties * self;
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		self = _data1_->self;
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (_data1_->deleter);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (self);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_slice_free (Block1Data, _data1_);
#line 483 "pkcs11-properties.c"
	}
}


static void ___lambda2_ (Block1Data* _data1_, GObject* obj, GAsyncResult* res) {
	SeahorsePkcs11Properties * self;
	GError * _inner_error_ = NULL;
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self = _data1_->self;
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (res != NULL);
#line 495 "pkcs11-properties.c"
	{
		gboolean _tmp0_ = FALSE;
		SeahorsePkcs11Deleter* _tmp1_ = NULL;
		GAsyncResult* _tmp2_ = NULL;
		gboolean _tmp3_ = FALSE;
#line 185 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp1_ = _data1_->deleter;
#line 185 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp2_ = res;
#line 185 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp3_ = seahorse_deleter_delete_finish ((SeahorseDeleter*) _tmp1_, _tmp2_, &_inner_error_);
#line 185 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp0_ = _tmp3_;
#line 185 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_inner_error_ != NULL) {
#line 511 "pkcs11-properties.c"
			goto __catch2_g_error;
		}
#line 185 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_tmp0_) {
#line 186 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			gtk_widget_destroy ((GtkWidget*) self);
#line 518 "pkcs11-properties.c"
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* err = NULL;
		const gchar* _tmp4_ = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		err = _inner_error_;
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_inner_error_ = NULL;
#line 188 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp4_ = _ ("Couldn't delete");
#line 188 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp5_ = err;
#line 188 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp6_ = _tmp5_->message;
#line 188 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_util_show_error ((GtkWidget*) self, _tmp4_, _tmp6_);
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_error_free0 (err);
#line 542 "pkcs11-properties.c"
	}
	__finally2:
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_inner_error_ != NULL) {
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_clear_error (&_inner_error_);
#line 184 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		return;
#line 553 "pkcs11-properties.c"
	}
}


static void ____lambda2__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	___lambda2_ (self, source_object, res);
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	block1_data_unref (self);
#line 563 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_on_delete_objects (SeahorsePkcs11Properties* self, GtkAction* action) {
	Block1Data* _data1_;
	GObject* partner = NULL;
	GckObject* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	GObject* _tmp2_ = NULL;
	gboolean _tmp4_ = FALSE;
	SeahorsePkcs11Deleter* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (action != NULL);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data1_->_ref_count_ = 1;
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data1_->self = g_object_ref (self);
#line 171 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = self->priv->_object;
#line 171 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_get ((GObject*) _tmp0_, "partner", &partner, NULL);
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp2_ = partner;
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp2_ != NULL) {
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp1_ = TRUE;
#line 596 "pkcs11-properties.c"
	} else {
		GckObject* _tmp3_ = NULL;
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp3_ = self->priv->_object;
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp1_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, SEAHORSE_PKCS11_TYPE_PRIVATE_KEY);
#line 603 "pkcs11-properties.c"
	}
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp4_ = _tmp1_;
#line 174 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp4_) {
#line 609 "pkcs11-properties.c"
		GckObject* _tmp5_ = NULL;
		SeahorsePkcs11KeyDeleter* _tmp6_ = NULL;
		SeahorsePkcs11Deleter* _tmp7_ = NULL;
		GObject* _tmp8_ = NULL;
		gboolean _tmp9_ = FALSE;
#line 175 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp5_ = self->priv->_object;
#line 175 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp6_ = seahorse_pkcs11_key_deleter_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, gck_object_get_type (), GckObject));
#line 175 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (_data1_->deleter);
#line 175 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_data1_->deleter = (SeahorsePkcs11Deleter*) _tmp6_;
#line 176 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp7_ = _data1_->deleter;
#line 176 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp8_ = partner;
#line 176 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp9_ = seahorse_deleter_add_object ((SeahorseDeleter*) _tmp7_, _tmp8_);
#line 176 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (!_tmp9_) {
#line 177 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			g_assert_not_reached ();
#line 633 "pkcs11-properties.c"
		}
	} else {
		GckObject* _tmp10_ = NULL;
		SeahorsePkcs11Deleter* _tmp11_ = NULL;
#line 179 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp10_ = self->priv->_object;
#line 179 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp11_ = seahorse_pkcs11_deleter_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp10_, gck_object_get_type (), GckObject));
#line 179 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (_data1_->deleter);
#line 179 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_data1_->deleter = _tmp11_;
#line 646 "pkcs11-properties.c"
	}
#line 182 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp12_ = _data1_->deleter;
#line 182 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp13_ = seahorse_deleter_prompt ((SeahorseDeleter*) _tmp12_, (GtkWindow*) self);
#line 182 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp13_) {
#line 654 "pkcs11-properties.c"
		SeahorsePkcs11Deleter* _tmp14_ = NULL;
		GCancellable* _tmp15_ = NULL;
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp14_ = _data1_->deleter;
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp15_ = self->priv->_cancellable;
#line 183 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_deleter_delete ((SeahorseDeleter*) _tmp14_, _tmp15_, ____lambda2__gasync_ready_callback, block1_data_ref (_data1_));
#line 663 "pkcs11-properties.c"
	}
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (partner);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	block1_data_unref (_data1_);
#line 169 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data1_ = NULL;
#line 671 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_on_request_certificate (SeahorsePkcs11Properties* self, GtkAction* action) {
	GckObject* _tmp0_ = NULL;
#line 194 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 194 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (action != NULL);
#line 195 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = self->priv->_request_key;
#line 195 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_request_prompt ((GtkWindow*) self, _tmp0_);
#line 685 "pkcs11-properties.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return _data2_;
#line 694 "pkcs11-properties.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 703 "pkcs11-properties.c"
		SeahorsePkcs11Properties * self;
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		self = _data2_->self;
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (_data2_->object);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (self);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_slice_free (Block2Data, _data2_);
#line 713 "pkcs11-properties.c"
	}
}


static void __lambda6_ (Block2Data* _data2_, GObject* obj, GAsyncResult* res) {
	SeahorsePkcs11Properties * self;
	GError * _inner_error_ = NULL;
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self = _data2_->self;
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (res != NULL);
#line 725 "pkcs11-properties.c"
	{
		gboolean _tmp0_ = FALSE;
		GAsyncResult* _tmp1_ = NULL;
		gboolean _tmp2_ = FALSE;
#line 213 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp1_ = res;
#line 213 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp2_ = gcr_certificate_request_capable_finish (_tmp1_, &_inner_error_);
#line 213 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp0_ = _tmp2_;
#line 213 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_inner_error_ != NULL) {
#line 738 "pkcs11-properties.c"
			goto __catch3_g_error;
		}
#line 213 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_tmp0_) {
#line 743 "pkcs11-properties.c"
			GtkAction* request = NULL;
			GtkActionGroup* _tmp3_ = NULL;
			GtkAction* _tmp4_ = NULL;
			GtkAction* _tmp5_ = NULL;
			GtkAction* _tmp6_ = NULL;
			GObject* _tmp7_ = NULL;
			GckObject* _tmp8_ = NULL;
#line 214 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp3_ = self->priv->_actions;
#line 214 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp4_ = gtk_action_group_get_action (_tmp3_, "request-certificate");
#line 214 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp5_ = _g_object_ref0 (_tmp4_);
#line 214 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			request = _tmp5_;
#line 215 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp6_ = request;
#line 215 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			gtk_action_set_visible (_tmp6_, TRUE);
#line 216 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp7_ = _data2_->object;
#line 216 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_tmp8_ = _g_object_ref0 ((GckObject*) G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, SEAHORSE_PKCS11_TYPE_PRIVATE_KEY, SeahorsePkcs11PrivateKey));
#line 216 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_g_object_unref0 (self->priv->_request_key);
#line 216 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			self->priv->_request_key = _tmp8_;
#line 213 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
			_g_object_unref0 (request);
#line 773 "pkcs11-properties.c"
		}
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* err = NULL;
		GError* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		err = _inner_error_;
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_inner_error_ = NULL;
#line 219 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp9_ = err;
#line 219 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp10_ = _tmp9_->message;
#line 219 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_message ("pkcs11-properties.vala:219: couldn't check capabilities of private key" \
": %s", _tmp10_);
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_error_free0 (err);
#line 794 "pkcs11-properties.c"
	}
	__finally3:
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_inner_error_ != NULL) {
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_clear_error (&_inner_error_);
#line 212 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		return;
#line 805 "pkcs11-properties.c"
	}
}


static void ___lambda6__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	__lambda6_ (self, source_object, res);
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	block2_data_unref (self);
#line 815 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_check_certificate_request_capable (SeahorsePkcs11Properties* self, GObject* object) {
	Block2Data* _data2_;
	GObject* _tmp0_ = NULL;
	GObject* _tmp1_ = NULL;
	GObject* _tmp2_ = NULL;
	GObject* _tmp3_ = NULL;
	GCancellable* _tmp4_ = NULL;
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (object != NULL);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data2_->_ref_count_ = 1;
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data2_->self = g_object_ref (self);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = object;
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (_data2_->object);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data2_->object = _tmp1_;
#line 208 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp2_ = _data2_->object;
#line 208 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, SEAHORSE_PKCS11_TYPE_PRIVATE_KEY)) {
#line 209 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		block2_data_unref (_data2_);
#line 209 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_data2_ = NULL;
#line 209 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		return;
#line 854 "pkcs11-properties.c"
	}
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp3_ = _data2_->object;
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp4_ = self->priv->_cancellable;
#line 211 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gcr_certificate_request_capable_async ((GckObject*) G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, SEAHORSE_PKCS11_TYPE_PRIVATE_KEY, SeahorsePkcs11PrivateKey), _tmp4_, ___lambda6__gasync_ready_callback, block2_data_ref (_data2_));
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	block2_data_unref (_data2_);
#line 207 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_data2_ = NULL;
#line 866 "pkcs11-properties.c"
}


GckObject* seahorse_pkcs11_properties_get_object (SeahorsePkcs11Properties* self) {
	GckObject* result;
	GckObject* _tmp0_ = NULL;
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = self->priv->_object;
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	result = _tmp0_;
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return result;
#line 881 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_set_object (SeahorsePkcs11Properties* self, GckObject* value) {
	GckObject* _tmp0_ = NULL;
	GckObject* _tmp1_ = NULL;
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (self != NULL);
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = value;
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_object);
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv->_object = _tmp1_;
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_notify ((GObject *) self, "object");
#line 900 "pkcs11-properties.c"
}


static void _seahorse_pkcs11_properties___lambda7_ (SeahorsePkcs11Properties* self, GtkWidget* widget) {
	GtkWidget* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GtkWidget* _tmp4_ = NULL;
	GtkWidget* _tmp5_ = NULL;
	GtkStyleContext* _tmp6_ = NULL;
	GtkWidget* _tmp7_ = NULL;
	GtkWidget* _tmp8_ = NULL;
#line 84 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_return_if_fail (widget != NULL);
#line 85 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = widget;
#line 85 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, GTK_TYPE_TOOLBAR)) {
#line 86 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		return;
#line 922 "pkcs11-properties.c"
	}
#line 88 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = self->priv->_content;
#line 88 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp2_ = widget;
#line 88 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_box_pack_start (_tmp1_, _tmp2_, FALSE, TRUE, (guint) 0);
#line 89 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp3_ = self->priv->_content;
#line 89 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp4_ = widget;
#line 89 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_box_reorder_child (_tmp3_, _tmp4_, 0);
#line 91 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp5_ = widget;
#line 91 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp6_ = gtk_widget_get_style_context (_tmp5_);
#line 91 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_style_context_add_class (_tmp6_, GTK_STYLE_CLASS_PRIMARY_TOOLBAR);
#line 92 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp7_ = widget;
#line 92 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_reset_style (_tmp7_);
#line 93 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp8_ = widget;
#line 93 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_show (_tmp8_);
#line 950 "pkcs11-properties.c"
}


static void __seahorse_pkcs11_properties___lambda7__gtk_ui_manager_add_widget (GtkUIManager* _sender, GtkWidget* widget, gpointer self) {
#line 84 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_seahorse_pkcs11_properties___lambda7_ (self, widget);
#line 957 "pkcs11-properties.c"
}


static void _seahorse_pkcs11_properties___lambda8_ (SeahorsePkcs11Properties* self) {
#line 102 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_update_label (self);
#line 964 "pkcs11-properties.c"
}


static void __seahorse_pkcs11_properties___lambda8__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 102 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_seahorse_pkcs11_properties___lambda8_ (self);
#line 971 "pkcs11-properties.c"
}


static GObject * seahorse_pkcs11_properties_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SeahorsePkcs11Properties * self;
	GCancellable* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GcrViewer* _tmp4_ = NULL;
	GcrViewer* _tmp5_ = NULL;
	GtkBox* _tmp6_ = NULL;
	GcrViewer* _tmp7_ = NULL;
	GcrViewer* _tmp8_ = NULL;
	GcrViewer* _tmp9_ = NULL;
	GcrViewer* _tmp10_ = NULL;
	GtkActionGroup* _tmp11_ = NULL;
	GtkActionGroup* _tmp12_ = NULL;
	GtkActionGroup* _tmp13_ = NULL;
	GtkAction* action = NULL;
	GtkActionGroup* _tmp14_ = NULL;
	GtkAction* _tmp15_ = NULL;
	GtkAction* _tmp16_ = NULL;
	GckObject* _tmp17_ = NULL;
	GtkAction* _tmp18_ = NULL;
	GtkActionGroup* _tmp19_ = NULL;
	GtkAction* _tmp20_ = NULL;
	GtkAction* _tmp21_ = NULL;
	GckObject* _tmp22_ = NULL;
	GtkAction* _tmp23_ = NULL;
	GtkAction* request = NULL;
	GtkActionGroup* _tmp24_ = NULL;
	GtkAction* _tmp25_ = NULL;
	GtkAction* _tmp26_ = NULL;
	GtkAction* _tmp27_ = NULL;
	GtkAction* _tmp28_ = NULL;
	GtkUIManager* _tmp29_ = NULL;
	GtkUIManager* _tmp30_ = NULL;
	GtkActionGroup* _tmp31_ = NULL;
	GtkUIManager* _tmp32_ = NULL;
	GtkUIManager* _tmp37_ = NULL;
	GckObject* _tmp38_ = NULL;
	GckObject* _tmp39_ = NULL;
	GckObject* _tmp40_ = NULL;
	GObject* partner = NULL;
	GckObject* _tmp41_ = NULL;
	GObject* _tmp42_ = NULL;
	GList* exporters = NULL;
	GckObject* _tmp45_ = NULL;
	GtkAction* export = NULL;
	GtkActionGroup* _tmp48_ = NULL;
	GtkAction* _tmp49_ = NULL;
	GtkAction* _tmp50_ = NULL;
	GtkAction* _tmp51_ = NULL;
	GList* _tmp52_ = NULL;
	GcrViewer* _tmp53_ = NULL;
	GError * _inner_error_ = NULL;
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	parent_class = G_OBJECT_CLASS (seahorse_pkcs11_properties_parent_class);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_PKCS11_TYPE_PROPERTIES, SeahorsePkcs11Properties);
#line 54 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = g_cancellable_new ();
#line 54 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_cancellable);
#line 54 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv->_cancellable = _tmp0_;
#line 55 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 400, 400);
#line 57 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp1_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 57 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_ref_sink (_tmp1_);
#line 57 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_content);
#line 57 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv->_content = _tmp1_;
#line 58 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp2_ = self->priv->_content;
#line 58 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp2_);
#line 59 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp3_ = self->priv->_content;
#line 59 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_show ((GtkWidget*) _tmp3_);
#line 61 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp4_ = gcr_viewer_new_scrolled ();
#line 61 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 61 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_viewer);
#line 61 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv->_viewer = _tmp5_;
#line 62 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp6_ = self->priv->_content;
#line 62 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp7_ = self->priv->_viewer;
#line 62 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_container_add ((GtkContainer*) _tmp6_, (GtkWidget*) _tmp7_);
#line 63 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp8_ = self->priv->_viewer;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp8_, TRUE);
#line 64 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp9_ = self->priv->_viewer;
#line 64 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp9_, TRUE);
#line 65 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp10_ = self->priv->_viewer;
#line 65 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_show ((GtkWidget*) _tmp10_);
#line 69 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp11_ = gtk_action_group_new ("Pkcs11Actions");
#line 69 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_actions);
#line 69 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv->_actions = _tmp11_;
#line 70 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp12_ = self->priv->_actions;
#line 70 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_action_group_set_translation_domain (_tmp12_, GETTEXT_PACKAGE);
#line 71 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp13_ = self->priv->_actions;
#line 71 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_action_group_add_actions (_tmp13_, SEAHORSE_PKCS11_PROPERTIES_UI_ACTIONS, G_N_ELEMENTS (SEAHORSE_PKCS11_PROPERTIES_UI_ACTIONS), self);
#line 72 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp14_ = self->priv->_actions;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp15_ = gtk_action_group_get_action (_tmp14_, "delete-object");
#line 72 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp16_ = _g_object_ref0 (_tmp15_);
#line 72 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	action = _tmp16_;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp17_ = self->priv->_object;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp18_ = action;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp17_, "deletable", (GObject*) _tmp18_, "sensitive", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 75 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp19_ = self->priv->_actions;
#line 75 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp20_ = gtk_action_group_get_action (_tmp19_, "export-object");
#line 75 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp21_ = _g_object_ref0 (_tmp20_);
#line 75 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (action);
#line 75 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	action = _tmp21_;
#line 76 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp22_ = self->priv->_object;
#line 76 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp23_ = action;
#line 76 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp22_, "exportable", (GObject*) _tmp23_, "sensitive", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 78 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp24_ = self->priv->_actions;
#line 78 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp25_ = gtk_action_group_get_action (_tmp24_, "request-certificate");
#line 78 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp26_ = _g_object_ref0 (_tmp25_);
#line 78 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	request = _tmp26_;
#line 79 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp27_ = request;
#line 79 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_action_set_is_important (_tmp27_, TRUE);
#line 80 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp28_ = request;
#line 80 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_action_set_visible (_tmp28_, FALSE);
#line 82 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp29_ = gtk_ui_manager_new ();
#line 82 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_ui_manager);
#line 82 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv->_ui_manager = _tmp29_;
#line 83 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp30_ = self->priv->_ui_manager;
#line 83 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp31_ = self->priv->_actions;
#line 83 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_ui_manager_insert_action_group (_tmp30_, _tmp31_, 0);
#line 84 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp32_ = self->priv->_ui_manager;
#line 84 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_signal_connect_object (_tmp32_, "add-widget", (GCallback) __seahorse_pkcs11_properties___lambda7__gtk_ui_manager_add_widget, self, 0);
#line 1163 "pkcs11-properties.c"
	{
		GtkUIManager* _tmp33_ = NULL;
		const gchar* _tmp34_ = NULL;
#line 96 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp33_ = self->priv->_ui_manager;
#line 96 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp34_ = seahorse_pkcs11_properties_UI_STRING;
#line 96 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		gtk_ui_manager_add_ui_from_string (_tmp33_, _tmp34_, (gssize) (-1), &_inner_error_);
#line 96 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		if (_inner_error_ != NULL) {
#line 1175 "pkcs11-properties.c"
			goto __catch4_g_error;
		}
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* err = NULL;
		GError* _tmp35_ = NULL;
		const gchar* _tmp36_ = NULL;
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		err = _inner_error_;
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_inner_error_ = NULL;
#line 98 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp35_ = err;
#line 98 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp36_ = _tmp35_->message;
#line 98 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_critical ("pkcs11-properties.vala:98: %s", _tmp36_);
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_error_free0 (err);
#line 1197 "pkcs11-properties.c"
	}
	__finally4:
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_inner_error_ != NULL) {
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (request);
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_g_object_unref0 (action);
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 95 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_clear_error (&_inner_error_);
#line 1210 "pkcs11-properties.c"
	}
#line 100 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp37_ = self->priv->_ui_manager;
#line 100 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_ui_manager_ensure_update (_tmp37_);
#line 102 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp38_ = self->priv->_object;
#line 102 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_signal_connect_object ((GObject*) _tmp38_, "notify::label", (GCallback) __seahorse_pkcs11_properties___lambda8__g_object_notify, self, 0);
#line 103 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_update_label (self);
#line 104 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp39_ = self->priv->_object;
#line 104 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_add_renderer_for_object (self, (GObject*) _tmp39_);
#line 105 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp40_ = self->priv->_object;
#line 105 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_check_certificate_request_capable (self, (GObject*) _tmp40_);
#line 108 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp41_ = self->priv->_object;
#line 108 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_get ((GObject*) _tmp41_, "partner", &partner, NULL);
#line 109 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp42_ = partner;
#line 109 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (_tmp42_ != NULL) {
#line 1238 "pkcs11-properties.c"
		GObject* _tmp43_ = NULL;
		GObject* _tmp44_ = NULL;
#line 110 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp43_ = partner;
#line 110 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_pkcs11_properties_add_renderer_for_object (self, _tmp43_);
#line 111 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp44_ = partner;
#line 111 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_pkcs11_properties_check_certificate_request_capable (self, _tmp44_);
#line 1249 "pkcs11-properties.c"
	}
#line 115 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp45_ = self->priv->_object;
#line 115 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp45_, SEAHORSE_TYPE_EXPORTABLE)) {
#line 1255 "pkcs11-properties.c"
		GckObject* _tmp46_ = NULL;
		GList* _tmp47_ = NULL;
#line 116 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp46_ = self->priv->_object;
#line 116 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		_tmp47_ = seahorse_exportable_create_exporters (G_TYPE_CHECK_INSTANCE_CAST (_tmp46_, SEAHORSE_TYPE_EXPORTABLE, SeahorseExportable), SEAHORSE_EXPORTER_TYPE_ANY);
#line 116 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		__g_list_free__g_object_unref0_0 (exporters);
#line 116 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		exporters = _tmp47_;
#line 1266 "pkcs11-properties.c"
	}
#line 118 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp48_ = self->priv->_actions;
#line 118 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp49_ = gtk_action_group_get_action (_tmp48_, "export-object");
#line 118 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp50_ = _g_object_ref0 (_tmp49_);
#line 118 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	export = _tmp50_;
#line 119 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp51_ = export;
#line 119 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp52_ = exporters;
#line 119 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_action_set_visible (_tmp51_, _tmp52_ != NULL);
#line 121 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp53_ = self->priv->_viewer;
#line 121 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	gtk_widget_grab_focus ((GtkWidget*) _tmp53_);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (export);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	__g_list_free__g_object_unref0_0 (exporters);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (partner);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (request);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (action);
#line 53 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	return obj;
#line 1298 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_class_init (SeahorsePkcs11PropertiesClass * klass) {
	gchar* _tmp0_ = NULL;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_parent_class = g_type_class_peek_parent (klass);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_type_class_add_private (klass, sizeof (SeahorsePkcs11PropertiesPrivate));
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (klass)->dispose = seahorse_pkcs11_properties_real_dispose;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_seahorse_pkcs11_properties_get_property;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_seahorse_pkcs11_properties_set_property;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (klass)->constructor = seahorse_pkcs11_properties_constructor;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (klass)->finalize = seahorse_pkcs11_properties_finalize;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAHORSE_PKCS11_PROPERTIES_OBJECT, g_param_spec_object ("object", "object", "object", gck_object_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 31 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_tmp0_ = g_strdup ("<ui>\n" \
"\t\t\t<toolbar name='Toolbar'>\n" \
"\t\t\t\t<toolitem action='export-object'/>\n" \
"\t\t\t\t<toolitem action='delete-object'/>\n" \
"\t\t\t\t<separator name='MiddleSeparator' expand='true'/>\n" \
"\t\t\t\t<toolitem action='request-certificate'/>\n" \
"\t\t\t</toolbar>\n" \
"\t\t</ui>");
#line 31 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	seahorse_pkcs11_properties_UI_STRING = _tmp0_;
#line 1324 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_instance_init (SeahorsePkcs11Properties * self) {
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self->priv = SEAHORSE_PKCS11_PROPERTIES_GET_PRIVATE (self);
#line 1331 "pkcs11-properties.c"
}


static void seahorse_pkcs11_properties_finalize (GObject* obj) {
	SeahorsePkcs11Properties * self;
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_PKCS11_TYPE_PROPERTIES, SeahorsePkcs11Properties);
#line 29 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_object);
#line 41 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_content);
#line 42 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_viewer);
#line 43 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_cancellable);
#line 44 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_request_key);
#line 45 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_ui_manager);
#line 46 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	_g_object_unref0 (self->priv->_actions);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	G_OBJECT_CLASS (seahorse_pkcs11_properties_parent_class)->finalize (obj);
#line 1355 "pkcs11-properties.c"
}


GType seahorse_pkcs11_properties_get_type (void) {
	static volatile gsize seahorse_pkcs11_properties_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_pkcs11_properties_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorsePkcs11PropertiesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_pkcs11_properties_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorsePkcs11Properties), 0, (GInstanceInitFunc) seahorse_pkcs11_properties_instance_init, NULL };
		GType seahorse_pkcs11_properties_type_id;
		seahorse_pkcs11_properties_type_id = g_type_register_static (GTK_TYPE_WINDOW, "SeahorsePkcs11Properties", &g_define_type_info, 0);
		g_once_init_leave (&seahorse_pkcs11_properties_type_id__volatile, seahorse_pkcs11_properties_type_id);
	}
	return seahorse_pkcs11_properties_type_id__volatile;
}


static void _vala_seahorse_pkcs11_properties_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeahorsePkcs11Properties * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_PKCS11_TYPE_PROPERTIES, SeahorsePkcs11Properties);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	switch (property_id) {
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		case SEAHORSE_PKCS11_PROPERTIES_OBJECT:
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		g_value_set_object (value, seahorse_pkcs11_properties_get_object (self));
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		break;
#line 1382 "pkcs11-properties.c"
		default:
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		break;
#line 1388 "pkcs11-properties.c"
	}
}


static void _vala_seahorse_pkcs11_properties_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeahorsePkcs11Properties * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAHORSE_PKCS11_TYPE_PROPERTIES, SeahorsePkcs11Properties);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
	switch (property_id) {
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		case SEAHORSE_PKCS11_PROPERTIES_OBJECT:
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		seahorse_pkcs11_properties_set_object (self, g_value_get_object (value));
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		break;
#line 1404 "pkcs11-properties.c"
		default:
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-properties.vala"
		break;
#line 1410 "pkcs11-properties.c"
	}
}



