/* pkcs11-deleter.c generated by valac 0.22.1, the Vala compiler
 * generated from pkcs11-deleter.vala, do not modify */

/*
 * Seahorse
 *
 * Copyright (C) 2013 Red Hat Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * Author: Stef Walter <stefw@redhat.com>
 */

#include <glib.h>
#include <glib-object.h>
#include "seahorse-pkcs11.h"
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include "seahorse-common.h"
#include <gck/gck.h>
#include <gio/gio.h>
#include <p11-kit/pkcs11.h>

#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
typedef struct _SeahorsePkcs11DeleterDeleteData SeahorsePkcs11DeleterDeleteData;

struct _SeahorsePkcs11DeleterDeleteData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	SeahorsePkcs11Deleter* self;
	GCancellable* cancellable;
	gboolean result;
	GList* objects;
	GList* _tmp0_;
	GList* _tmp1_;
	GList* _tmp2_;
	GList* object_collection;
	GList* object_it;
	GckObject* object;
	GckObject* _tmp3_;
	GCancellable* _tmp4_;
	SeahorsePkcs11Token* token;
	GckObject* _tmp5_;
	SeahorsePkcs11Token* _tmp6_;
	SeahorsePkcs11Token* _tmp7_;
	GckObject* _tmp8_;
	GError* e;
	gboolean _tmp9_;
	GError* _tmp10_;
	GQuark _tmp11_;
	GQuark _tmp12_;
	GError* _tmp13_;
	gint _tmp14_;
	gboolean _tmp15_;
	GError* _tmp16_;
	GError* _tmp17_;
	GError * _inner_error_;
};


static gpointer seahorse_pkcs11_deleter_parent_class = NULL;

enum  {
	SEAHORSE_PKCS11_DELETER_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
static GtkDialog* seahorse_pkcs11_deleter_real_create_confirm (SeahorseDeleter* base, GtkWindow* parent);
static GList* seahorse_pkcs11_deleter_real_get_objects (SeahorseDeleter* base);
static gboolean seahorse_pkcs11_deleter_real_add_object (SeahorseDeleter* base, GObject* obj);
static void seahorse_pkcs11_deleter_real_delete_data_free (gpointer _data);
static void seahorse_pkcs11_deleter_real_delete (SeahorseDeleter* base, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean seahorse_pkcs11_deleter_real_delete_co (SeahorsePkcs11DeleterDeleteData* _data_);
static void seahorse_pkcs11_deleter_delete_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void seahorse_pkcs11_deleter_finalize (GObject* obj);


static void _g_object_unref0_ (gpointer var) {
#line 28 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 103 "pkcs11-deleter.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 28 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_list_free (self);
#line 112 "pkcs11-deleter.c"
}


static GtkDialog* seahorse_pkcs11_deleter_real_create_confirm (SeahorseDeleter* base, GtkWindow* parent) {
	SeahorsePkcs11Deleter * self;
	GtkDialog* result = NULL;
	guint num = 0U;
	GList* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
#line 30 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	self = (SeahorsePkcs11Deleter*) base;
#line 31 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp0_ = self->objects;
#line 31 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp1_ = g_list_length (_tmp0_);
#line 31 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	num = _tmp1_;
#line 32 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp2_ = num;
#line 32 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	if (_tmp2_ == ((guint) 1)) {
#line 135 "pkcs11-deleter.c"
		gchar* label = NULL;
		GList* _tmp3_ = NULL;
		gconstpointer _tmp4_ = NULL;
		GtkWindow* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		SeahorseDeleteDialog* _tmp8_ = NULL;
#line 34 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp3_ = self->objects;
#line 34 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp4_ = _tmp3_->data;
#line 34 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_object_get ((GObject*) ((GckObject*) _tmp4_), "label", &label, NULL);
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp5_ = parent;
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp6_ = _ ("Are you sure you want to permanently delete %s?");
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp7_ = label;
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp8_ = (SeahorseDeleteDialog*) seahorse_delete_dialog_new (_tmp5_, _tmp6_, _tmp7_, NULL);
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_object_ref_sink (_tmp8_);
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		result = (GtkDialog*) _tmp8_;
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_g_free0 (label);
#line 35 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		return result;
#line 165 "pkcs11-deleter.c"
	} else {
		GtkWindow* _tmp9_ = NULL;
		guint _tmp10_ = 0U;
		const gchar* _tmp11_ = NULL;
		guint _tmp12_ = 0U;
		SeahorseDeleteDialog* _tmp13_ = NULL;
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp9_ = parent;
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp10_ = num;
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp11_ = ngettext ("Are you sure you want to permanently delete %d certificate?", "Are you sure you want to permanently delete %d certificates?", (gulong) _tmp10_);
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp12_ = num;
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp13_ = (SeahorseDeleteDialog*) seahorse_delete_dialog_new (_tmp9_, _tmp11_, _tmp12_, NULL);
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_object_ref_sink (_tmp13_);
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		result = (GtkDialog*) _tmp13_;
#line 37 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		return result;
#line 188 "pkcs11-deleter.c"
	}
}


SeahorsePkcs11Deleter* seahorse_pkcs11_deleter_construct (GType object_type, GckObject* object) {
	SeahorsePkcs11Deleter * self = NULL;
	GckObject* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 42 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_return_val_if_fail (object != NULL, NULL);
#line 42 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	self = (SeahorsePkcs11Deleter*) seahorse_deleter_construct (object_type);
#line 43 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp0_ = object;
#line 43 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp1_ = seahorse_deleter_add_object ((SeahorseDeleter*) self, (GObject*) _tmp0_);
#line 43 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	if (!_tmp1_) {
#line 44 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_assert_not_reached ();
#line 209 "pkcs11-deleter.c"
	}
#line 42 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return self;
#line 213 "pkcs11-deleter.c"
}


SeahorsePkcs11Deleter* seahorse_pkcs11_deleter_new (GckObject* object) {
#line 42 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return seahorse_pkcs11_deleter_construct (SEAHORSE_PKCS11_TYPE_DELETER, object);
#line 220 "pkcs11-deleter.c"
}


static GList* seahorse_pkcs11_deleter_real_get_objects (SeahorseDeleter* base) {
	SeahorsePkcs11Deleter * self;
	GList* result = NULL;
	GList* _tmp0_ = NULL;
#line 47 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	self = (SeahorsePkcs11Deleter*) base;
#line 48 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp0_ = self->objects;
#line 48 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	result = _tmp0_;
#line 48 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return result;
#line 236 "pkcs11-deleter.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 53 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return self ? g_object_ref (self) : NULL;
#line 243 "pkcs11-deleter.c"
}


static gboolean seahorse_pkcs11_deleter_real_add_object (SeahorseDeleter* base, GObject* obj) {
	SeahorsePkcs11Deleter * self;
	gboolean result = FALSE;
	GObject* _tmp0_ = NULL;
#line 51 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	self = (SeahorsePkcs11Deleter*) base;
#line 51 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_return_val_if_fail (obj != NULL, FALSE);
#line 52 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp0_ = obj;
#line 52 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, SEAHORSE_PKCS11_TYPE_CERTIFICATE)) {
#line 259 "pkcs11-deleter.c"
		GObject* _tmp1_ = NULL;
		GckObject* _tmp2_ = NULL;
#line 53 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp1_ = obj;
#line 53 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gck_object_get_type (), GckObject));
#line 53 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		self->objects = g_list_append (self->objects, _tmp2_);
#line 54 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		result = TRUE;
#line 54 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		return result;
#line 272 "pkcs11-deleter.c"
	}
#line 56 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	result = FALSE;
#line 56 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return result;
#line 278 "pkcs11-deleter.c"
}


static void seahorse_pkcs11_deleter_real_delete_data_free (gpointer _data) {
	SeahorsePkcs11DeleterDeleteData* _data_;
	_data_ = _data;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_g_object_unref0 (_data_->cancellable);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_g_object_unref0 (_data_->self);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_slice_free (SeahorsePkcs11DeleterDeleteData, _data_);
#line 291 "pkcs11-deleter.c"
}


static void seahorse_pkcs11_deleter_real_delete (SeahorseDeleter* base, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	SeahorsePkcs11Deleter * self;
	SeahorsePkcs11DeleterDeleteData* _data_;
	SeahorsePkcs11Deleter* _tmp0_ = NULL;
	GCancellable* _tmp1_ = NULL;
	GCancellable* _tmp2_ = NULL;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	self = (SeahorsePkcs11Deleter*) base;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_ = g_slice_new0 (SeahorsePkcs11DeleterDeleteData);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, seahorse_pkcs11_deleter_real_delete);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, seahorse_pkcs11_deleter_real_delete_data_free);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->self = _tmp0_;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp1_ = cancellable;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_g_object_unref0 (_data_->cancellable);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->cancellable = _tmp2_;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	seahorse_pkcs11_deleter_real_delete_co (_data_);
#line 323 "pkcs11-deleter.c"
}


static gboolean seahorse_pkcs11_deleter_real_delete_finish (SeahorseDeleter* base, GAsyncResult* _res_, GError** error) {
	gboolean result;
	SeahorsePkcs11DeleterDeleteData* _data_;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		return FALSE;
#line 334 "pkcs11-deleter.c"
	}
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	result = _data_->result;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return result;
#line 342 "pkcs11-deleter.c"
}


static void seahorse_pkcs11_deleter_delete_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	SeahorsePkcs11DeleterDeleteData* _data_;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_ = _user_data_;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_source_object_ = source_object;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_res_ = _res_;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	seahorse_pkcs11_deleter_real_delete_co (_data_);
#line 356 "pkcs11-deleter.c"
}


static gpointer _g_error_copy0 (gpointer self) {
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return self ? g_error_copy (self) : NULL;
#line 363 "pkcs11-deleter.c"
}


static gboolean seahorse_pkcs11_deleter_real_delete_co (SeahorsePkcs11DeleterDeleteData* _data_) {
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	switch (_data_->_state_) {
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		case 0:
#line 372 "pkcs11-deleter.c"
		goto _state_0;
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		case 1:
#line 376 "pkcs11-deleter.c"
		goto _state_1;
		default:
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_assert_not_reached ();
#line 381 "pkcs11-deleter.c"
	}
	_state_0:
#line 60 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_tmp0_ = NULL;
#line 60 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_tmp0_ = _data_->self->objects;
#line 60 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_tmp1_ = NULL;
#line 60 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_tmp1_ = g_list_copy (_data_->_tmp0_);
#line 60 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->objects = _data_->_tmp1_;
#line 61 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_tmp2_ = NULL;
#line 61 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->_tmp2_ = _data_->objects;
#line 398 "pkcs11-deleter.c"
	{
#line 61 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		_data_->object_collection = _data_->_tmp2_;
#line 61 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		for (_data_->object_it = _data_->object_collection; _data_->object_it != NULL; _data_->object_it = _data_->object_it->next) {
#line 61 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
			_data_->object = (GckObject*) _data_->object_it->data;
#line 406 "pkcs11-deleter.c"
			{
				{
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp3_ = NULL;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp3_ = _data_->object;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp4_ = NULL;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp4_ = _data_->cancellable;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_state_ = 1;
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					gck_object_destroy_async (_data_->_tmp3_, _data_->_tmp4_, seahorse_pkcs11_deleter_delete_ready, _data_);
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					return FALSE;
#line 423 "pkcs11-deleter.c"
					_state_1:
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					gck_object_destroy_finish (_data_->_tmp3_, _data_->_res_, &_data_->_inner_error_);
#line 63 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					if (_data_->_inner_error_ != NULL) {
#line 429 "pkcs11-deleter.c"
						goto __catch0_g_error;
					}
#line 66 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp5_ = NULL;
#line 66 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp5_ = _data_->object;
#line 66 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					g_object_get ((GObject*) _data_->_tmp5_, "place", &_data_->token, NULL);
#line 67 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp6_ = NULL;
#line 67 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp6_ = _data_->token;
#line 67 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					if (_data_->_tmp6_ != NULL) {
#line 68 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp7_ = NULL;
#line 68 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp7_ = _data_->token;
#line 68 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp8_ = NULL;
#line 68 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp8_ = _data_->object;
#line 68 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						seahorse_pkcs11_token_remove_object (_data_->_tmp7_, _data_->_tmp8_);
#line 454 "pkcs11-deleter.c"
					}
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_g_object_unref0 (_data_->token);
#line 458 "pkcs11-deleter.c"
				}
				goto __finally0;
				__catch0_g_error:
				{
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->e = _data_->_inner_error_;
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_inner_error_ = NULL;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp10_ = NULL;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp10_ = _data_->e;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp11_ = 0U;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp11_ = _data_->_tmp10_->domain;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp12_ = 0U;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp12_ = gck_error_get_quark ();
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					if (_data_->_tmp11_ != _data_->_tmp12_) {
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp9_ = TRUE;
#line 483 "pkcs11-deleter.c"
					} else {
#line 73 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp13_ = NULL;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp13_ = _data_->e;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp14_ = 0;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp14_ = _data_->_tmp13_->code;
#line 73 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp9_ = ((gulong) _data_->_tmp14_) != CKR_OBJECT_HANDLE_INVALID;
#line 495 "pkcs11-deleter.c"
					}
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp15_ = FALSE;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_data_->_tmp15_ = _data_->_tmp9_;
#line 72 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					if (_data_->_tmp15_) {
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp16_ = NULL;
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp16_ = _data_->e;
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp17_ = NULL;
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_tmp17_ = _g_error_copy0 (_data_->_tmp16_);
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_data_->_inner_error_ = _data_->_tmp17_;
#line 74 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						_g_error_free0 (_data_->e);
#line 515 "pkcs11-deleter.c"
						goto __finally0;
					}
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_g_error_free0 (_data_->e);
#line 520 "pkcs11-deleter.c"
				}
				__finally0:
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
				if (_data_->_inner_error_ != NULL) {
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					g_error_free (_data_->_inner_error_);
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					_g_list_free0 (_data_->objects);
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					if (_data_->_state_ == 0) {
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 535 "pkcs11-deleter.c"
					} else {
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
						g_simple_async_result_complete (_data_->_async_result);
#line 539 "pkcs11-deleter.c"
					}
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					g_object_unref (_data_->_async_result);
#line 62 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
					return FALSE;
#line 545 "pkcs11-deleter.c"
				}
			}
		}
	}
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_data_->result = TRUE;
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_g_list_free0 (_data_->objects);
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	if (_data_->_state_ == 0) {
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 558 "pkcs11-deleter.c"
	} else {
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 562 "pkcs11-deleter.c"
	}
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_object_unref (_data_->_async_result);
#line 77 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return FALSE;
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	_g_list_free0 (_data_->objects);
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	if (_data_->_state_ == 0) {
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 574 "pkcs11-deleter.c"
	} else {
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 578 "pkcs11-deleter.c"
	}
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	g_object_unref (_data_->_async_result);
#line 59 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	return FALSE;
#line 584 "pkcs11-deleter.c"
}


static void seahorse_pkcs11_deleter_class_init (SeahorsePkcs11DeleterClass * klass) {
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	seahorse_pkcs11_deleter_parent_class = g_type_class_peek_parent (klass);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	SEAHORSE_DELETER_CLASS (klass)->create_confirm = seahorse_pkcs11_deleter_real_create_confirm;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	SEAHORSE_DELETER_CLASS (klass)->get_objects = seahorse_pkcs11_deleter_real_get_objects;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	SEAHORSE_DELETER_CLASS (klass)->add_object = seahorse_pkcs11_deleter_real_add_object;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	SEAHORSE_DELETER_CLASS (klass)->delete = seahorse_pkcs11_deleter_real_delete;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	SEAHORSE_DELETER_CLASS (klass)->delete_finish = seahorse_pkcs11_deleter_real_delete_finish;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	G_OBJECT_CLASS (klass)->finalize = seahorse_pkcs11_deleter_finalize;
#line 603 "pkcs11-deleter.c"
}


static void seahorse_pkcs11_deleter_instance_init (SeahorsePkcs11Deleter * self) {
}


static void seahorse_pkcs11_deleter_finalize (GObject* obj) {
	SeahorsePkcs11Deleter * self;
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAHORSE_PKCS11_TYPE_DELETER, SeahorsePkcs11Deleter);
#line 28 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	__g_list_free__g_object_unref0_0 (self->objects);
#line 27 "/data/src/seahorse/pkcs11/pkcs11-deleter.vala"
	G_OBJECT_CLASS (seahorse_pkcs11_deleter_parent_class)->finalize (obj);
#line 619 "pkcs11-deleter.c"
}


GType seahorse_pkcs11_deleter_get_type (void) {
	static volatile gsize seahorse_pkcs11_deleter_type_id__volatile = 0;
	if (g_once_init_enter (&seahorse_pkcs11_deleter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeahorsePkcs11DeleterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seahorse_pkcs11_deleter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeahorsePkcs11Deleter), 0, (GInstanceInitFunc) seahorse_pkcs11_deleter_instance_init, NULL };
		GType seahorse_pkcs11_deleter_type_id;
		seahorse_pkcs11_deleter_type_id = g_type_register_static (SEAHORSE_TYPE_DELETER, "SeahorsePkcs11Deleter", &g_define_type_info, 0);
		g_once_init_leave (&seahorse_pkcs11_deleter_type_id__volatile, seahorse_pkcs11_deleter_type_id);
	}
	return seahorse_pkcs11_deleter_type_id__volatile;
}



